import type { Subject } from "../types";

export const allemand: Subject = {
  id: "allemand",
  name: "Allemand",
  icon: "🇩🇪",
  colorFrom: "from-amber-500",
  colorTo: "to-yellow-600",
  chapters: [
    {
      id: "revision-5eme-salutations",
      title: "Révision 5ème : salutations",
      description: "Premiers mots et expressions de base",
      icon: "👋",
      exercises: [
        {
          id: "de-r5-q01",
          type: "qcm",
          prompt: '"Guten Tag" signifie :',
          options: ["Bonjour", "Au revoir", "Merci", "Pardon"],
          correctIndex: 0,
        },
        {
          id: "de-r5-q02",
          type: "qcm",
          prompt: "Comment dit-on « merci » en allemand ?",
          options: ["Danke", "Bitte", "Tschüss", "Entschuldigung"],
          correctIndex: 0,
        },
        {
          id: "de-r5-q03",
          type: "fill-blank",
          prompt: "Comment demande-t-on « Comment t'appelles-tu ? » : Wie ___ du?",
          acceptedAnswers: ["heißt"],
        },
        {
          id: "de-r5-q04",
          type: "true-false",
          prompt: "En allemand, tous les noms communs s'écrivent avec une majuscule.",
          correct: true,
        },
        {
          id: "de-r5-q05",
          type: "qcm",
          prompt: '"Auf Wiedersehen" signifie :',
          options: ["Au revoir", "Bonjour", "Merci", "Oui"],
          correctIndex: 0,
        },
        {
          id: "de-r5-q06",
          type: "qcm",
          prompt: "Comment dit-on « oui » en allemand ?",
          options: ["Ja", "Nein", "Bitte", "Danke"],
          correctIndex: 0,
        },
        {
          id: "de-r5-q07",
          type: "fill-blank",
          prompt: "Comment dit-on « non » en allemand ?",
          acceptedAnswers: ["nein"],
        },
        {
          id: "de-r5-q08",
          type: "true-false",
          prompt: '"Bitte" peut signifier à la fois « s\'il te plaît » et « je t\'en prie ».',
          correct: true,
        },
        {
          id: "de-r5-q09",
          type: "qcm",
          prompt: '"Wie geht\'s?" signifie :',
          options: ["Comment ça va ?", "Comment tu t'appelles ?", "Où habites-tu ?", "Quel âge as-tu ?"],
          correctIndex: 0,
        },
        {
          id: "de-r5-q10",
          type: "fill-blank",
          prompt: "Conjugue « sein » (être) à la 1ère personne du singulier : ich ___.",
          acceptedAnswers: ["bin"],
        },
      ],
    },
    {
      id: "presentations-4eme",
      title: "Se présenter au présent",
      description: "Conjugaison de verbes réguliers et questions (4ème)",
      icon: "🗣️",
      exercises: [
        {
          id: "de-pres-q01",
          type: "fill-blank",
          prompt: "Conjugue « wohnen » (habiter) : ich ___.",
          acceptedAnswers: ["wohne"],
        },
        {
          id: "de-pres-q02",
          type: "fill-blank",
          prompt: "Conjugue « wohnen » (habiter) : du ___.",
          acceptedAnswers: ["wohnst"],
        },
        {
          id: "de-pres-q03",
          type: "qcm",
          prompt: "Comment demande-t-on « Où habites-tu ? » ?",
          options: ["Wo wohnst du?", "Wie heißt du?", "Wie geht's?", "Was machst du?"],
          correctIndex: 0,
        },
        {
          id: "de-pres-q04",
          type: "true-false",
          prompt: '"Mein Name ist..." signifie "Mon nom est...".',
          correct: true,
        },
        {
          id: "de-pres-q05",
          type: "fill-blank",
          prompt: "Conjugue « kommen » (venir) : ich ___.",
          acceptedAnswers: ["komme"],
        },
        {
          id: "de-pres-q06",
          type: "qcm",
          prompt: "Comment demande-t-on l'âge de quelqu'un ?",
          options: ["Wie alt bist du?", "Wie heißt du?", "Wo bist du?", "Was ist das?"],
          correctIndex: 0,
        },
        {
          id: "de-pres-q07",
          type: "fill-blank",
          prompt: "Réponds : Ich bin zwölf Jahre ___.",
          acceptedAnswers: ["alt"],
        },
        {
          id: "de-pres-q08",
          type: "true-false",
          prompt: "En allemand, le verbe conjugué se place en général en deuxième position dans une phrase déclarative.",
          correct: true,
        },
        {
          id: "de-pres-q09",
          type: "qcm",
          prompt: '"Ich komme aus Frankreich" signifie :',
          options: ["Je viens de France", "J'habite en France", "Je vais en France", "J'aime la France"],
          correctIndex: 0,
        },
        {
          id: "de-pres-q10",
          type: "fill-blank",
          prompt: "Conjugue « spielen » (jouer) : du ___.",
          acceptedAnswers: ["spielst"],
        },
      ],
    },
  ],
};
