import type { Subject } from "../types";

export const anglais: Subject = {
  id: "anglais",
  name: "Anglais",
  icon: "🇬🇧",
  colorFrom: "from-sky-500",
  colorTo: "to-cyan-600",
  chapters: [
    {
      id: "revision-5eme-present-simple",
      title: "Révision 5ème : present simple",
      description: "Conjugaison de base et vocabulaire courant",
      icon: "📘",
      exercises: [
        {
          id: "ang-r5-q01",
          type: "qcm",
          prompt: 'Comment forme-t-on la 3e personne du singulier au présent simple pour "play" ?',
          options: ["plays", "play", "playing", "played"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q02",
          type: "fill-blank",
          prompt: "She ___ (have) a dog.",
          acceptedAnswers: ["has"],
        },
        {
          id: "ang-r5-q03",
          type: "true-false",
          prompt: '"I am, you are, he is" est la conjugaison du verbe "to be" au présent.',
          correct: true,
        },
        {
          id: "ang-r5-q04",
          type: "qcm",
          prompt: 'Que signifie "always" ?',
          options: ["toujours", "jamais", "parfois", "souvent"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q05",
          type: "fill-blank",
          prompt: "They ___ (not/like) vegetables.",
          acceptedAnswers: ["do not like", "don't like"],
        },
        {
          id: "ang-r5-q06",
          type: "qcm",
          prompt: 'Quel est le pluriel de "child" ?',
          options: ["children", "childs", "childes", "child"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q07",
          type: "true-false",
          prompt: "On ajoute « -s » à la fin du verbe à la 3e personne du singulier au présent simple.",
          correct: true,
        },
        {
          id: "ang-r5-q08",
          type: "qcm",
          prompt: 'Que signifie "yesterday" ?',
          options: ["hier", "demain", "aujourd'hui", "maintenant"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q09",
          type: "fill-blank",
          prompt: "What ___ your name?",
          acceptedAnswers: ["is"],
        },
        {
          id: "ang-r5-q10",
          type: "qcm",
          prompt: 'Quel est le contraire de "big" ?',
          options: ["small", "tall", "fast", "happy"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "present-perfect",
      title: "The Present Perfect",
      description: "have/has + participe passé, since/for, already/yet (4ème)",
      icon: "📗",
      exercises: [
        {
          id: "ang-pp-q01",
          type: "fill-blank",
          prompt: "She ___ (live) in Paris for five years.",
          acceptedAnswers: ["has lived"],
        },
        {
          id: "ang-pp-q02",
          type: "qcm",
          prompt: "Quelle structure utilise-t-on pour former le present perfect ?",
          options: [
            "have/has + participe passé",
            "be + -ing",
            "will + verbe",
            "did + verbe",
          ],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q03",
          type: "fill-blank",
          prompt: "I ___ (never/see) this movie.",
          acceptedAnswers: ["have never seen"],
        },
        {
          id: "ang-pp-q04",
          type: "true-false",
          prompt: "On utilise « since » avec une durée (since 5 years) et « for » avec un point de départ (for 2010).",
          correct: false,
          explanation: "C'est l'inverse : « since » + point de départ dans le temps (since 2010), « for » + durée (for 5 years).",
        },
        {
          id: "ang-pp-q05",
          type: "qcm",
          prompt: 'Quel est le participe passé de "go" ?',
          options: ["gone", "went", "going", "goed"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q06",
          type: "fill-blank",
          prompt: "They ___ (just/finish) their homework.",
          acceptedAnswers: ["have just finished"],
        },
        {
          id: "ang-pp-q07",
          type: "qcm",
          prompt: 'Quel est le participe passé de "eat" ?',
          options: ["eaten", "ate", "eating", "eated"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q08",
          type: "true-false",
          prompt: '"Have you ever been to London?" est une question correcte au present perfect.',
          correct: true,
        },
        {
          id: "ang-pp-q09",
          type: "fill-blank",
          prompt: "We ___ (not/visit) Italy yet.",
          acceptedAnswers: ["have not visited", "haven't visited"],
        },
        {
          id: "ang-pp-q10",
          type: "qcm",
          prompt: 'Quel mot signifie "déjà" en anglais (utilisé dans une phrase affirmative) ?',
          options: ["already", "yet", "since", "ago"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q11",
          type: "qcm",
          prompt: "Quel mot utilise-t-on plutôt dans une phrase négative ou interrogative pour « déjà / encore » ?",
          options: ["yet", "already", "just", "ever"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q12",
          type: "qcm",
          prompt: 'Quel temps utilise-t-on avec une date précise comme "last year" ?',
          options: ["Le prétérit (past simple)", "Le present perfect", "Le present simple", "Le futur"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q13",
          type: "true-false",
          prompt: "Le present perfect ne s'utilise jamais avec une date précise comme « in 2010 ».",
          correct: true,
        },
        {
          id: "ang-pp-q14",
          type: "fill-blank",
          prompt: "My parents ___ (be) married for 20 years.",
          acceptedAnswers: ["have been"],
        },
        {
          id: "ang-pp-q15",
          type: "qcm",
          prompt: 'Quel est le participe passé de "do" ?',
          options: ["done", "did", "doing", "doed"],
          correctIndex: 0,
        },
      ],
    },
  ],
};
