import type { Subject } from "../types";

export const anglais: Subject = {
  id: "anglais",
  name: "Anglais",
  icon: "🇬🇧",
  colorFrom: "from-sky-500",
  colorTo: "to-cyan-600",
  chapters: [
    {
      id: "revision-5eme-present-simple",
      title: "Révision 5ème : present simple",
      description: "Conjugaison de base et vocabulaire courant",
      icon: "📘",
      exercises: [
        {
          id: "ang-r5-q01",
          type: "qcm",
          prompt: 'Comment forme-t-on la 3e personne du singulier au présent simple pour "play" ?',
          options: ["plays", "play", "playing", "played"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q02",
          type: "fill-blank",
          prompt: "She ___ (have) a dog.",
          acceptedAnswers: ["has"],
        },
        {
          id: "ang-r5-q03",
          type: "true-false",
          prompt: '"I am, you are, he is" est la conjugaison du verbe "to be" au présent.',
          correct: true,
        },
        {
          id: "ang-r5-q04",
          type: "qcm",
          prompt: 'Que signifie "always" ?',
          options: ["toujours", "jamais", "parfois", "souvent"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q05",
          type: "fill-blank",
          prompt: "They ___ (not/like) vegetables.",
          acceptedAnswers: ["do not like", "don't like"],
        },
        {
          id: "ang-r5-q06",
          type: "qcm",
          prompt: 'Quel est le pluriel de "child" ?',
          options: ["children", "childs", "childes", "child"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q07",
          type: "true-false",
          prompt: "On ajoute « -s » à la fin du verbe à la 3e personne du singulier au présent simple.",
          correct: true,
        },
        {
          id: "ang-r5-q08",
          type: "qcm",
          prompt: 'Que signifie "yesterday" ?',
          options: ["hier", "demain", "aujourd'hui", "maintenant"],
          correctIndex: 0,
        },
        {
          id: "ang-r5-q09",
          type: "fill-blank",
          prompt: "What ___ your name?",
          acceptedAnswers: ["is"],
        },
        {
          id: "ang-r5-q10",
          type: "qcm",
          prompt: 'Quel est le contraire de "big" ?',
          options: ["small", "tall", "fast", "happy"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "present-perfect",
      title: "The Present Perfect",
      description: "have/has + participe passé, since/for, already/yet (4ème)",
      icon: "📗",
      exercises: [
        {
          id: "ang-pp-q01",
          type: "fill-blank",
          prompt: "She ___ (live) in Paris for five years.",
          acceptedAnswers: ["has lived"],
        },
        {
          id: "ang-pp-q02",
          type: "qcm",
          prompt: "Quelle structure utilise-t-on pour former le present perfect ?",
          options: [
            "have/has + participe passé",
            "be + -ing",
            "will + verbe",
            "did + verbe",
          ],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q03",
          type: "fill-blank",
          prompt: "I ___ (never/see) this movie.",
          acceptedAnswers: ["have never seen"],
        },
        {
          id: "ang-pp-q04",
          type: "true-false",
          prompt: "On utilise « since » avec une durée (since 5 years) et « for » avec un point de départ (for 2010).",
          correct: false,
          explanation: "C'est l'inverse : « since » + point de départ dans le temps (since 2010), « for » + durée (for 5 years).",
        },
        {
          id: "ang-pp-q05",
          type: "qcm",
          prompt: 'Quel est le participe passé de "go" ?',
          options: ["gone", "went", "going", "goed"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q06",
          type: "fill-blank",
          prompt: "They ___ (just/finish) their homework.",
          acceptedAnswers: ["have just finished"],
        },
        {
          id: "ang-pp-q07",
          type: "qcm",
          prompt: 'Quel est le participe passé de "eat" ?',
          options: ["eaten", "ate", "eating", "eated"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q08",
          type: "true-false",
          prompt: '"Have you ever been to London?" est une question correcte au present perfect.',
          correct: true,
        },
        {
          id: "ang-pp-q09",
          type: "fill-blank",
          prompt: "We ___ (not/visit) Italy yet.",
          acceptedAnswers: ["have not visited", "haven't visited"],
        },
        {
          id: "ang-pp-q10",
          type: "qcm",
          prompt: 'Quel mot signifie "déjà" en anglais (utilisé dans une phrase affirmative) ?',
          options: ["already", "yet", "since", "ago"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q11",
          type: "qcm",
          prompt: "Quel mot utilise-t-on plutôt dans une phrase négative ou interrogative pour « déjà / encore » ?",
          options: ["yet", "already", "just", "ever"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q12",
          type: "qcm",
          prompt: 'Quel temps utilise-t-on avec une date précise comme "last year" ?',
          options: ["Le prétérit (past simple)", "Le present perfect", "Le present simple", "Le futur"],
          correctIndex: 0,
        },
        {
          id: "ang-pp-q13",
          type: "true-false",
          prompt: "Le present perfect ne s'utilise jamais avec une date précise comme « in 2010 ».",
          correct: true,
        },
        {
          id: "ang-pp-q14",
          type: "fill-blank",
          prompt: "My parents ___ (be) married for 20 years.",
          acceptedAnswers: ["have been"],
        },
        {
          id: "ang-pp-q15",
          type: "qcm",
          prompt: 'Quel est le participe passé de "do" ?',
          options: ["done", "did", "doing", "doed"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "past-simple",
      title: "The Past Simple",
      description: "Le prétérit, verbes réguliers et irréguliers",
      icon: "📙",
      exercises: [
        { id: "ang-ps-q01", type: "fill-blank", prompt: "I ___ (visit) my grandmother last week.", acceptedAnswers: ["visited"] },
        { id: "ang-ps-q02", type: "qcm", prompt: 'Quel est le prétérit du verbe irrégulier "go" ?', options: ["went", "goed", "gone", "going"], correctIndex: 0 },
        { id: "ang-ps-q03", type: "true-false", prompt: "Pour les verbes réguliers, on ajoute « -ed » au prétérit.", correct: true },
        { id: "ang-ps-q04", type: "fill-blank", prompt: "She ___ (not/go) to school yesterday.", acceptedAnswers: ["did not go", "didn't go"] },
        { id: "ang-ps-q05", type: "qcm", prompt: "Quelle structure utilise-t-on pour poser une question au prétérit ?", options: ["Did + sujet + verbe", "Have + sujet + verbe", "Will + sujet + verbe", "Be + sujet + verbe"], correctIndex: 0 },
        { id: "ang-ps-q06", type: "qcm", prompt: 'Quel est le prétérit de "see" ?', options: ["saw", "seen", "seed", "seeing"], correctIndex: 0 },
        { id: "ang-ps-q07", type: "true-false", prompt: "Le prétérit s'utilise pour une action terminée à un moment précis du passé.", correct: true },
        { id: "ang-ps-q08", type: "fill-blank", prompt: "They ___ (play) football yesterday afternoon.", acceptedAnswers: ["played"] },
        { id: "ang-ps-q09", type: "qcm", prompt: "Quel mot indique souvent qu'on doit utiliser le prétérit ?", options: ["yesterday", "never", "since", "already"], correctIndex: 0 },
        { id: "ang-ps-q10", type: "qcm", prompt: 'Quel est le prétérit de "have" ?', options: ["had", "haved", "have", "having"], correctIndex: 0 },
      ],
    },
    {
      id: "comparatifs-superlatifs",
      title: "Comparatives and Superlatives",
      description: "Comparer et exprimer le degré supérieur en anglais",
      icon: "⚖️",
      exercises: [
        { id: "ang-cs-q01", type: "qcm", prompt: 'Comment forme-t-on le comparatif de "tall" ?', options: ["taller", "more tall", "tallest", "talliest"], correctIndex: 0 },
        { id: "ang-cs-q02", type: "fill-blank", prompt: "This book is ___ (interesting) than that one.", acceptedAnswers: ["more interesting"] },
        { id: "ang-cs-q03", type: "true-false", prompt: "Pour les adjectifs courts (1 syllabe), on ajoute « -er » au comparatif.", correct: true },
        { id: "ang-cs-q04", type: "qcm", prompt: 'Quel est le superlatif de "good" ?', options: ["the best", "the goodest", "the better", "the most good"], correctIndex: 0 },
        { id: "ang-cs-q05", type: "qcm", prompt: 'Quel est le comparatif de "bad" ?', options: ["worse", "badder", "more bad", "worst"], correctIndex: 0 },
        { id: "ang-cs-q06", type: "fill-blank", prompt: "She is the ___ (tall) student in the class.", acceptedAnswers: ["tallest"] },
        { id: "ang-cs-q07", type: "true-false", prompt: "Pour les adjectifs longs (3 syllabes ou plus), on utilise « more » + adjectif + « than ».", correct: true },
        { id: "ang-cs-q08", type: "qcm", prompt: 'Comment dit-on "aussi grand que" en anglais ?', options: ["as tall as", "more tall as", "tall than", "as tall than"], correctIndex: 0 },
        { id: "ang-cs-q09", type: "fill-blank", prompt: "This is the ___ (expensive) phone in the shop.", acceptedAnswers: ["most expensive"] },
        { id: "ang-cs-q10", type: "qcm", prompt: 'Quel est le superlatif de "big" ?', options: ["the biggest", "the most big", "the bigger", "biggest"], correctIndex: 0 },
      ],
    },
    {
      id: "modaux-futur",
      title: "Modal Verbs and the Future",
      description: "Can, must, should, have to, going to et will",
      icon: "🔮",
      exercises: [
        { id: "ang-mf-q01", type: "qcm", prompt: 'Que signifie "must" ?', options: ["devoir (obligation forte)", "pouvoir", "vouloir", "aimer"], correctIndex: 0 },
        { id: "ang-mf-q02", type: "true-false", prompt: '"Can" exprime la capacité ou la permission.', correct: true },
        { id: "ang-mf-q03", type: "fill-blank", prompt: "You ___ smoke here. (interdiction)", acceptedAnswers: ["must not", "mustn't"] },
        { id: "ang-mf-q04", type: "qcm", prompt: "Quelle structure exprime une intention/prévision future ?", options: ["going to", "must", "can", "should"], correctIndex: 0 },
        { id: "ang-mf-q05", type: "qcm", prompt: "Quelle structure exprime un conseil ?", options: ["should", "must", "can", "will"], correctIndex: 0 },
        { id: "ang-mf-q06", type: "fill-blank", prompt: "I ___ call you tomorrow.", acceptedAnswers: ["will"] },
        { id: "ang-mf-q07", type: "true-false", prompt: '"Have to" exprime une obligation, souvent imposée par une règle extérieure.', correct: true },
        { id: "ang-mf-q08", type: "qcm", prompt: "Quelle phrase exprime une capacité ?", options: ["I can swim.", "I must swim.", "I will swim.", "I should swim."], correctIndex: 0 },
        { id: "ang-mf-q09", type: "fill-blank", prompt: "It ___ rain tomorrow, I think.", acceptedAnswers: ["will not", "won't"] },
        { id: "ang-mf-q10", type: "qcm", prompt: "Quel modal exprime une forte probabilité/déduction logique ?", options: ["must", "can", "will", "should"], correctIndex: 0 },
      ],
    },
  ],
};
