import type { Subject } from "../types";

export const chinois: Subject = {
  id: "chinois",
  name: "Chinois",
  icon: "🀄",
  colorFrom: "from-fuchsia-500",
  colorTo: "to-pink-600",
  chapters: [
    {
      id: "revision-5eme-salutations",
      title: "Révision 5ème : salutations et tons",
      description: "Premiers mots, pinyin et tons du mandarin",
      icon: "👋",
      exercises: [
        {
          id: "cn-r5-q01",
          type: "qcm",
          prompt: "Que signifie « 你好 » (nǐ hǎo) ?",
          options: ["Bonjour", "Au revoir", "Merci", "S'il vous plaît"],
          correctIndex: 0,
        },
        {
          id: "cn-r5-q02",
          type: "qcm",
          prompt: "Comment dit-on « merci » en chinois (pinyin) ?",
          options: ["xièxiè", "zàijiàn", "duìbuqǐ", "qǐng"],
          correctIndex: 0,
        },
        {
          id: "cn-r5-q03",
          type: "true-false",
          prompt: "Le mandarin utilise des tons qui changent le sens d'un mot.",
          correct: true,
        },
        {
          id: "cn-r5-q04",
          type: "qcm",
          prompt: "Combien de tons principaux compte le mandarin standard ?",
          options: ["4", "2", "6", "8"],
          correctIndex: 0,
        },
        {
          id: "cn-r5-q05",
          type: "fill-blank",
          prompt: "Le mot chinois pour « au revoir » se prononce zài___.",
          acceptedAnswers: ["jiàn", "jian"],
        },
        {
          id: "cn-r5-q06",
          type: "true-false",
          prompt: "Le pinyin est un système de transcription qui utilise l'alphabet latin pour écrire la prononciation du chinois.",
          correct: true,
        },
        {
          id: "cn-r5-q07",
          type: "qcm",
          prompt: "Comment dit-on « je » en chinois (pinyin) ?",
          options: ["wǒ", "nǐ", "tā", "wǒmen"],
          correctIndex: 0,
        },
        {
          id: "cn-r5-q08",
          type: "qcm",
          prompt: "Que signifie « 对不起 » (duìbuqǐ) ?",
          options: ["Pardon / excusez-moi", "Merci", "Bonjour", "Au revoir"],
          correctIndex: 0,
        },
        {
          id: "cn-r5-q09",
          type: "fill-blank",
          prompt: "« Nǐ hǎo » signifie ___.",
          acceptedAnswers: ["bonjour"],
        },
        {
          id: "cn-r5-q10",
          type: "qcm",
          prompt: "Que signifie « 请 » (qǐng) ?",
          options: ["S'il vous plaît", "Merci", "Pardon", "Bonjour"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "vocabulaire-4eme",
      title: "Nombres et famille",
      description: "Vocabulaire de base : nombres, famille, jours (4ème)",
      icon: "🏠",
      exercises: [
        {
          id: "cn-voc-q01",
          type: "qcm",
          prompt: "Comment dit-on « un » (1) en chinois (pinyin) ?",
          options: ["yī", "èr", "sān", "sì"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q02",
          type: "qcm",
          prompt: "Comment dit-on « deux » (2) en chinois (pinyin) ?",
          options: ["èr", "yī", "sān", "sì"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q03",
          type: "fill-blank",
          prompt: "« Sān » (三) signifie le chiffre ___.",
          acceptedAnswers: ["3", "trois"],
        },
        {
          id: "cn-voc-q04",
          type: "qcm",
          prompt: "Comment dit-on « mère » en chinois (pinyin) ?",
          options: ["māma", "bàba", "gēge", "jiějie"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q05",
          type: "qcm",
          prompt: "Comment dit-on « père » en chinois (pinyin) ?",
          options: ["bàba", "māma", "dìdi", "mèimei"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q06",
          type: "true-false",
          prompt: "« Xīngqī yī » signifie « lundi ».",
          correct: true,
        },
        {
          id: "cn-voc-q07",
          type: "fill-blank",
          prompt: "Comment dit-on « dix » (10) en pinyin ?",
          acceptedAnswers: ["shí", "shi"],
        },
        {
          id: "cn-voc-q08",
          type: "qcm",
          prompt: "Que signifie « 朋友 » (péngyou) ?",
          options: ["Ami", "Famille", "École", "Maison"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q09",
          type: "qcm",
          prompt: "Comment dit-on « grand frère » en chinois (pinyin) ?",
          options: ["gēge", "jiějie", "dìdi", "mèimei"],
          correctIndex: 0,
        },
        {
          id: "cn-voc-q10",
          type: "fill-blank",
          prompt: "Comment dit-on « école » en pinyin ? xué___",
          acceptedAnswers: ["xiào", "xiao"],
        },
      ],
    },
  ],
};
