import type { Subject } from "../types";

export const francais4eme: Subject = {
  id: "francais-4eme",
  name: "Français",
  icon: "📖",
  colorFrom: "from-purple-500",
  colorTo: "to-pink-500",
  chapters: [
    {
      id: "subjonctif-present",
      title: "Le subjonctif présent",
      description: "Conjugaison et emploi du subjonctif",
      icon: "✍️",
      exercises: [
        {
          id: "fr-subj-q01",
          type: "fill-blank",
          prompt: "Il faut que tu ___ (finir) tes devoirs.",
          acceptedAnswers: ["finisses"],
        },
        {
          id: "fr-subj-q02",
          type: "fill-blank",
          prompt: "Je voudrais qu'elle ___ (venir) avec nous.",
          acceptedAnswers: ["vienne"],
        },
        {
          id: "fr-subj-q03",
          type: "qcm",
          prompt: "Quel mode utilise-t-on après « il faut que » ?",
          options: ["L'indicatif", "Le subjonctif", "Le conditionnel", "L'impératif"],
          correctIndex: 1,
        },
        {
          id: "fr-subj-q04",
          type: "fill-blank",
          prompt: "Il faut que nous ___ (être) à l'heure.",
          acceptedAnswers: ["soyons"],
        },
        {
          id: "fr-subj-q05",
          type: "fill-blank",
          prompt: "Il faut que vous ___ (avoir) de la patience.",
          acceptedAnswers: ["ayez"],
        },
        {
          id: "fr-subj-q06",
          type: "fill-blank",
          prompt: "Il faut qu'il ___ (faire) ses devoirs.",
          acceptedAnswers: ["fasse"],
        },
        {
          id: "fr-subj-q07",
          type: "qcm",
          prompt: "Quelle terminaison retrouve-t-on à la 1ère personne du singulier du subjonctif présent pour la plupart des verbes ?",
          options: ["-e", "-es", "-ons", "-ez"],
          correctIndex: 0,
        },
        {
          id: "fr-subj-q08",
          type: "fill-blank",
          prompt: "Bien qu'il ___ (pleuvoir), nous sortirons.",
          acceptedAnswers: ["pleuve"],
        },
        {
          id: "fr-subj-q09",
          type: "true-false",
          prompt: "Le subjonctif présent du verbe « aller » à la 3e personne du singulier est « aille ».",
          correct: true,
        },
        {
          id: "fr-subj-q10",
          type: "fill-blank",
          prompt: "Je souhaite que tu ___ (réussir) ton examen.",
          acceptedAnswers: ["réussisses"],
        },
        {
          id: "fr-subj-q11",
          type: "qcm",
          prompt: "Laquelle de ces expressions n'introduit PAS le subjonctif ?",
          options: ["il faut que", "je pense que", "je veux que", "bien que"],
          correctIndex: 1,
          explanation: "« Je pense que » est suivi de l'indicatif, contrairement aux autres expressions de volonté, de but ou de concession.",
        },
        {
          id: "fr-subj-q12",
          type: "fill-blank",
          prompt: "Il faut que je ___ (savoir) la réponse.",
          acceptedAnswers: ["sache"],
        },
        {
          id: "fr-subj-q13",
          type: "true-false",
          prompt: "Après « avant que », on utilise le subjonctif.",
          correct: true,
        },
        {
          id: "fr-subj-q14",
          type: "fill-blank",
          prompt: "Il faut qu'ils ___ (pouvoir) participer.",
          acceptedAnswers: ["puissent"],
        },
        {
          id: "fr-subj-q15",
          type: "qcm",
          prompt: "Quel est le radical du subjonctif présent du verbe « prendre » pour je/tu/il/ils ?",
          options: ["prend-", "prenn-", "prena-", "pren-"],
          correctIndex: 1,
        },
      ],
    },
    {
      id: "conditionnel",
      title: "Le conditionnel présent",
      description: "Formation et emploi du conditionnel",
      icon: "💭",
      exercises: [
        { id: "fr-cond-q01", type: "fill-blank", prompt: "Si j'avais de l'argent, je ___ (acheter) une maison.", acceptedAnswers: ["achèterais"] },
        { id: "fr-cond-q02", type: "qcm", prompt: "Le conditionnel présent exprime souvent :", options: ["un fait imaginaire ou soumis à une condition", "un ordre", "une certitude absolue", "une habitude"], correctIndex: 0 },
        { id: "fr-cond-q03", type: "fill-blank", prompt: "Tu ___ (pouvoir) m'aider, s'il te plaît ?", acceptedAnswers: ["pourrais"] },
        { id: "fr-cond-q04", type: "true-false", prompt: "Le conditionnel présent se forme à partir du radical du futur + les terminaisons de l'imparfait.", correct: true },
        { id: "fr-cond-q05", type: "fill-blank", prompt: "Nous ___ (aimer) venir avec vous.", acceptedAnswers: ["aimerions"] },
        { id: "fr-cond-q06", type: "qcm", prompt: "Quelle terminaison a « je » au conditionnel présent ?", options: ["-ais", "-ait", "-ons", "-ez"], correctIndex: 0 },
        { id: "fr-cond-q07", type: "fill-blank", prompt: "S'il faisait beau, nous ___ (sortir).", acceptedAnswers: ["sortirions"] },
        { id: "fr-cond-q08", type: "true-false", prompt: "Le conditionnel peut aussi exprimer la politesse (ex : « Je voudrais... »).", correct: true },
        { id: "fr-cond-q09", type: "qcm", prompt: "Quel est le conditionnel présent de « être » à la 3e personne du singulier ?", options: ["il serait", "il sera", "il était", "il soit"], correctIndex: 0 },
        { id: "fr-cond-q10", type: "fill-blank", prompt: "Ils ___ (devoir) réviser davantage.", acceptedAnswers: ["devraient"] },
      ],
    },
    {
      id: "types-formes-phrases",
      title: "Types et formes de phrases",
      description: "Déclarative, interrogative, injonctive, exclamative, négative",
      icon: "❓",
      exercises: [
        { id: "fr-typ-q01", type: "qcm", prompt: "Quel type de phrase exprime une question ?", options: ["La phrase interrogative", "La phrase déclarative", "La phrase injonctive", "La phrase exclamative"], correctIndex: 0 },
        { id: "fr-typ-q02", type: "true-false", prompt: "Une phrase exclamative exprime un sentiment fort (joie, surprise, colère...).", correct: true },
        { id: "fr-typ-q03", type: "qcm", prompt: "« Range ta chambre ! » est une phrase :", options: ["injonctive", "interrogative", "déclarative", "exclamative"], correctIndex: 0 },
        { id: "fr-typ-q04", type: "fill-blank", prompt: "La forme négative d'une phrase utilise souvent les mots ne... ___.", acceptedAnswers: ["pas"] },
        { id: "fr-typ-q05", type: "qcm", prompt: "Quelle phrase est à la forme négative ?", options: ["Je ne mange pas de viande.", "Je mange de la viande.", "Mange de la viande !", "Manges-tu de la viande ?"], correctIndex: 0 },
        { id: "fr-typ-q06", type: "true-false", prompt: "Une phrase déclarative se termine toujours par un point d'exclamation.", correct: false },
        { id: "fr-typ-q07", type: "qcm", prompt: "« Quel beau temps ! » est une phrase :", options: ["exclamative", "interrogative", "injonctive", "négative"], correctIndex: 0 },
        { id: "fr-typ-q08", type: "fill-blank", prompt: "Une phrase qui donne un ordre ou un conseil est une phrase ___.", acceptedAnswers: ["injonctive"] },
        { id: "fr-typ-q09", type: "true-false", prompt: "Une phrase peut être à la fois interrogative et négative (ex : « Ne viens-tu pas ? »).", correct: true },
        { id: "fr-typ-q10", type: "qcm", prompt: "Quelle est la forme interrogative correcte de « Tu viens. » ?", options: ["Viens-tu ?", "Tu viens !", "Viens.", "Tu ne viens pas."], correctIndex: 0 },
      ],
    },
    {
      id: "discours-rapporte",
      title: "Le discours rapporté",
      description: "Discours direct et discours indirect",
      icon: "💬",
      exercises: [
        { id: "fr-dr-q01", type: "qcm", prompt: "Au discours direct, les paroles sont rapportées :", options: ["exactement comme elles ont été dites", "avec des modifications grammaticales", "sans aucune ponctuation particulière", "uniquement au passé"], correctIndex: 0 },
        { id: "fr-dr-q02", type: "true-false", prompt: "Le discours direct est généralement encadré par des guillemets.", correct: true },
        { id: "fr-dr-q03", type: "qcm", prompt: "Transforme : Il dit : « Je viendrai demain. » → Il dit qu'il ___ demain.", options: ["viendra", "viendrait", "vienne", "vient"], correctIndex: 0 },
        { id: "fr-dr-q04", type: "fill-blank", prompt: "Au discours indirect, on supprime les ___ et on utilise des mots de liaison comme « que ».", acceptedAnswers: ["guillemets"] },
        { id: "fr-dr-q05", type: "true-false", prompt: "Au discours indirect, les pronoms personnels et les temps peuvent changer.", correct: true },
        { id: "fr-dr-q06", type: "qcm", prompt: "Elle me demande : « Où vas-tu ? » → Elle me demande ___.", options: ["où je vais", "où vas-tu", "si je vais", "que je vais"], correctIndex: 0 },
        { id: "fr-dr-q07", type: "true-false", prompt: "Le discours indirect introduit souvent la parole rapportée par un verbe comme « dire », « demander » ou « répondre » suivi de « que » ou « si ».", correct: true },
        { id: "fr-dr-q08", type: "qcm", prompt: "Quel mot introduit une question fermée (oui/non) au discours indirect ?", options: ["si", "que", "où", "quand"], correctIndex: 0 },
        { id: "fr-dr-q09", type: "qcm", prompt: "« Il a dit : “J'ai faim.” » devient au discours indirect : « Il a dit qu'il ___ faim. »", options: ["avait", "a", "aura", "ait"], correctIndex: 0 },
        { id: "fr-dr-q10", type: "true-false", prompt: "Au discours indirect, « demain » (après un verbe introducteur au passé) devient souvent « le lendemain ».", correct: true },
      ],
    },
    {
      id: "propositions-subordonnees",
      title: "Les propositions subordonnées",
      description: "Relatives, conjonctives, cause, temps, but, concession",
      icon: "🔗",
      exercises: [
        { id: "fr-ps-q01", type: "qcm", prompt: "Une proposition subordonnée dépend :", options: ["d'une proposition principale", "de rien", "uniquement d'un adjectif", "d'un nom propre"], correctIndex: 0 },
        { id: "fr-ps-q02", type: "true-false", prompt: "Une proposition subordonnée relative commence souvent par « qui », « que », « où », « dont ».", correct: true },
        { id: "fr-ps-q03", type: "qcm", prompt: "Dans « Je sais que tu as raison. », la subordonnée est :", options: ["que tu as raison", "je sais", "tu as raison seulement", "aucune"], correctIndex: 0 },
        { id: "fr-ps-q04", type: "fill-blank", prompt: "La proposition subordonnée relative complète un ___.", acceptedAnswers: ["nom", "groupe nominal"] },
        { id: "fr-ps-q05", type: "qcm", prompt: "Quelle conjonction introduit une subordonnée de cause ?", options: ["parce que", "et", "mais", "ou"], correctIndex: 0 },
        { id: "fr-ps-q06", type: "true-false", prompt: "« Quand il pleut, je reste à la maison. » contient une subordonnée de temps.", correct: true },
        { id: "fr-ps-q07", type: "qcm", prompt: "Quelle conjonction introduit une subordonnée de but ?", options: ["pour que", "parce que", "alors que", "bien que"], correctIndex: 0 },
        { id: "fr-ps-q08", type: "fill-blank", prompt: "« Bien qu'il soit fatigué, il continue. » : la subordonnée exprime la ___.", acceptedAnswers: ["concession", "opposition"] },
        { id: "fr-ps-q09", type: "true-false", prompt: "Une proposition subordonnée conjonctive est introduite par une conjonction de subordination (que, quand, si, parce que...).", correct: true },
        { id: "fr-ps-q10", type: "qcm", prompt: "Dans « Le livre que j'ai lu est passionnant. », « que j'ai lu » est une subordonnée :", options: ["relative", "complétive", "circonstancielle de temps", "interrogative"], correctIndex: 0 },
      ],
    },
    {
      id: "homophones",
      title: "Les homophones grammaticaux",
      description: "a/à, on/ont, son/sont, ce/se, ces/ses, où/ou...",
      icon: "🔍",
      exercises: [
        { id: "fr-ho-q01", type: "fill-blank", prompt: "Complète : Marie ___ (a/à) un chien.", acceptedAnswers: ["a"] },
        { id: "fr-ho-q02", type: "fill-blank", prompt: "Complète : Il va ___ (a/à) l'école.", acceptedAnswers: ["à"] },
        { id: "fr-ho-q03", type: "qcm", prompt: "Quel mot complète : « Les enfants ___ joué dehors. » ?", options: ["ont", "on", "en", "ans"], correctIndex: 0 },
        { id: "fr-ho-q04", type: "true-false", prompt: "« On » est un pronom, « ont » est le verbe avoir conjugué.", correct: true },
        { id: "fr-ho-q05", type: "fill-blank", prompt: "Complète : Paul et Lucie ___ (son/sont) en retard.", acceptedAnswers: ["sont"] },
        { id: "fr-ho-q06", type: "qcm", prompt: "Quel mot complète : « Regarde ___ chaussures, elles sont à toi. » ?", options: ["ces", "ses", "c'est", "s'est"], correctIndex: 0 },
        { id: "fr-ho-q07", type: "fill-blank", prompt: "Complète : Le chat ___ (ce/se) lave.", acceptedAnswers: ["se"] },
        { id: "fr-ho-q08", type: "qcm", prompt: "« C'est » ou « S'est » : « ___ parti tôt ce matin. »", options: ["Il s'est", "Il c'est"], correctIndex: 0 },
        { id: "fr-ho-q09", type: "true-false", prompt: "« Leur » est invariable devant un verbe (ex : « Je leur parle »), mais « leurs » s'accorde devant un nom pluriel (ex : « leurs livres »).", correct: true },
        { id: "fr-ho-q10", type: "fill-blank", prompt: "Complète : Je ne sais pas ___ (où/ou) il habite.", acceptedAnswers: ["où"] },
        { id: "fr-ho-q11", type: "qcm", prompt: "Quel mot complète : « Tu prends un café ___ un thé ? »", options: ["ou", "où"], correctIndex: 0 },
        { id: "fr-ho-q12", type: "fill-blank", prompt: "Complète : Le ciel ___ (et/est) bleu aujourd'hui.", acceptedAnswers: ["est"] },
      ],
    },
    {
      id: "accord-participe-passe",
      title: "L'accord du participe passé",
      description: "Avec être, avec avoir et les verbes pronominaux",
      icon: "✅",
      exercises: [
        { id: "fr-ap-q01", type: "qcm", prompt: "Avec l'auxiliaire « être », le participe passé s'accorde avec :", options: ["le sujet", "le COD", "rien", "le verbe"], correctIndex: 0 },
        { id: "fr-ap-q02", type: "fill-blank", prompt: "Elle est ___ (partir) tôt.", acceptedAnswers: ["partie"] },
        { id: "fr-ap-q03", type: "true-false", prompt: "Avec l'auxiliaire « avoir », le participe passé s'accorde avec le COD seulement si celui-ci est placé avant le verbe.", correct: true },
        { id: "fr-ap-q04", type: "fill-blank", prompt: "Les fleurs que j'ai ___ (cueillir) sont belles.", acceptedAnswers: ["cueillies"] },
        { id: "fr-ap-q05", type: "qcm", prompt: "« Les pommes, je les ai ___. » (manger)", options: ["mangées", "mangé", "mangés", "mangée"], correctIndex: 0 },
        { id: "fr-ap-q06", type: "true-false", prompt: "« J'ai mangé des pommes. » : le participe passé ne s'accorde pas car le COD « des pommes » est placé après le verbe.", correct: true },
        { id: "fr-ap-q07", type: "fill-blank", prompt: "Ils sont ___ (arriver) en avance.", acceptedAnswers: ["arrivés"] },
        { id: "fr-ap-q08", type: "qcm", prompt: "« Elle a ___ (faire) ses devoirs. »", options: ["fait", "faite", "faits", "faites"], correctIndex: 0 },
        { id: "fr-ap-q09", type: "true-false", prompt: "Avec les verbes pronominaux (se laver, se lever...), le participe passé s'accorde souvent avec le sujet.", correct: true },
        { id: "fr-ap-q10", type: "fill-blank", prompt: "Elles se sont ___ (laver) les mains.", acceptedAnswers: ["lavé"] },
      ],
    },
    {
      id: "figures-style-vocabulaire",
      title: "Figures de style et vocabulaire",
      description: "Métaphore, comparaison, hyperbole, synonymes et antonymes",
      icon: "🎨",
      exercises: [
        { id: "fr-fs-q01", type: "qcm", prompt: "« Il pleut des cordes » est une expression qui utilise :", options: ["une métaphore", "une comparaison", "une personnification", "une antithèse"], correctIndex: 0 },
        { id: "fr-fs-q02", type: "qcm", prompt: "« Le vent chantait dans les arbres » est :", options: ["une personnification", "une comparaison", "une hyperbole", "une antithèse"], correctIndex: 0 },
        { id: "fr-fs-q03", type: "fill-blank", prompt: "Une comparaison utilise souvent les mots « comme », « tel que » ou « ___ que ».", acceptedAnswers: ["ainsi"] },
        { id: "fr-fs-q04", type: "true-false", prompt: "Une métaphore est une comparaison sans mot de comparaison (comme, tel que...).", correct: true },
        { id: "fr-fs-q05", type: "qcm", prompt: "« Cette valise pèse une tonne ! » est une :", options: ["hyperbole (exagération)", "litote", "antithèse", "allitération"], correctIndex: 0 },
        { id: "fr-fs-q06", type: "qcm", prompt: "« Il n'est pas idiot » pour dire qu'il est intelligent est :", options: ["une litote", "une métaphore", "une comparaison", "une personnification"], correctIndex: 0 },
        { id: "fr-fs-q07", type: "fill-blank", prompt: "La répétition d'un même son au début de plusieurs mots s'appelle une ___.", acceptedAnswers: ["allitération"] },
        { id: "fr-fs-q08", type: "true-false", prompt: "Une antithèse rapproche deux idées opposées dans une même phrase.", correct: true },
        { id: "fr-fs-q09", type: "qcm", prompt: "Quel est un synonyme de « joyeux » ?", options: ["content", "triste", "fâché", "fatigué"], correctIndex: 0 },
        { id: "fr-fs-q10", type: "qcm", prompt: "Quel est un antonyme de « rapide » ?", options: ["lent", "vite", "pressé", "agile"], correctIndex: 0 },
      ],
    },
    {
      id: "comprehension-texte",
      title: "Compréhension de texte",
      description: "Lire un court récit et répondre à des questions",
      icon: "📰",
      exercises: [
        {
          id: "fr-ct-q01",
          type: "qcm",
          prompt:
            "Léo n'aimait pas se lever tôt. Chaque matin, il restait sous sa couette en espérant que le temps s'arrête. Mais ce jour-là, son réveil sonna plus fort que d'habitude. Il se souvint alors que c'était le jour de la sortie scolaire au musée des sciences. Soudain, il bondit hors du lit, plein d'énergie. Il s'habilla en un temps record et avala son petit-déjeuner sans même s'asseoir. Pour la première fois depuis longtemps, Léo avait envie d'aller à l'école.\n\nComment Léo se sent-il habituellement le matin ?",
          options: ["Il n'aime pas se lever", "Il est toujours en avance", "Il adore se lever tôt", "Il ne dort jamais"],
          correctIndex: 0,
        },
        {
          id: "fr-ct-q02",
          type: "qcm",
          prompt: "(Texte de Léo) Pourquoi Léo se lève-t-il vite ce jour-là ?",
          options: [
            "C'est le jour de la sortie au musée",
            "Il est en retard pour l'école",
            "Son réveil ne sonne pas",
            "Il a un examen",
          ],
          correctIndex: 0,
        },
        {
          id: "fr-ct-q03",
          type: "true-false",
          prompt: "(Texte de Léo) Léo s'habille lentement ce matin-là.",
          correct: false,
        },
        {
          id: "fr-ct-q04",
          type: "fill-blank",
          prompt: "(Texte de Léo) Léo va visiter le musée des ___.",
          acceptedAnswers: ["sciences"],
        },
        {
          id: "fr-ct-q05",
          type: "qcm",
          prompt: "(Texte de Léo) Quel sentiment éprouve Léo à la fin du texte ?",
          options: ["De l'enthousiasme", "De la tristesse", "De la peur", "De l'ennui"],
          correctIndex: 0,
        },
        {
          id: "fr-ct-q06",
          type: "true-false",
          prompt: "(Texte de Léo) Léo prend son temps pour le petit-déjeuner.",
          correct: false,
        },
        {
          id: "fr-ct-q07",
          type: "qcm",
          prompt: "(Texte de Léo) Quelle phrase montre que c'est inhabituel pour Léo de vouloir aller à l'école ?",
          options: [
            "« Pour la première fois depuis longtemps »",
            "« Chaque matin »",
            "« Il restait sous sa couette »",
            "« Il bondit hors du lit »",
          ],
          correctIndex: 0,
        },
      ],
    },
  ],
};
