import type { Subject } from "../types";

export const maths4eme: Subject = {
  id: "maths-4eme",
  name: "Maths",
  icon: "🔢",
  colorFrom: "from-blue-500",
  colorTo: "to-indigo-600",
  chapters: [
    {
      id: "nombres-relatifs",
      title: "Nombres relatifs",
      description: "Addition, soustraction, multiplication, division",
      icon: "➖",
      exercises: [
        {
          id: "maths-nr-q01",
          type: "qcm",
          prompt: "(-5) + 3 = ?",
          options: ["-8", "-2", "2", "8"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q02",
          type: "qcm",
          prompt: "7 + (-10) = ?",
          options: ["-17", "-3", "3", "17"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q03",
          type: "qcm",
          prompt: "(-4) - (-6) = ?",
          options: ["-10", "-2", "2", "10"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q04",
          type: "qcm",
          prompt: "(-3) × 5 = ?",
          options: ["-15", "-8", "8", "15"],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q05",
          type: "qcm",
          prompt: "(-6) × (-2) = ?",
          options: ["-12", "-4", "4", "12"],
          correctIndex: 3,
        },
        {
          id: "maths-nr-q06",
          type: "qcm",
          prompt: "(-12) ÷ 4 = ?",
          options: ["-8", "-3", "3", "8"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q07",
          type: "true-false",
          prompt: "-8 est plus petit que -3.",
          correct: true,
          explanation: "Sur la droite numérique, plus on va vers la gauche, plus le nombre est petit. -8 est plus à gauche que -3.",
        },
        {
          id: "maths-nr-q08",
          type: "qcm",
          prompt: "Quelle est la valeur absolue de -7 ?",
          options: ["-7", "0", "7", "14"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q09",
          type: "fill-blank",
          prompt: "Le résultat de (-9) + 9 est ___.",
          acceptedAnswers: ["0"],
        },
        {
          id: "maths-nr-q10",
          type: "qcm",
          prompt: "(-2) × (-3) × (-1) = ?",
          options: ["-6", "-1", "1", "6"],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q11",
          type: "qcm",
          prompt: "Range -5 ; 2 ; -1 ; 0 dans l'ordre croissant.",
          options: [
            "-5 < -1 < 0 < 2",
            "-1 < -5 < 0 < 2",
            "2 < 0 < -1 < -5",
            "0 < -1 < -5 < 2",
          ],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q12",
          type: "qcm",
          prompt: "5 - (-3) = ?",
          options: ["2", "-2", "8", "-8"],
          correctIndex: 2,
          explanation: "Soustraire un nombre négatif équivaut à ajouter son opposé : 5 - (-3) = 5 + 3 = 8.",
        },
        {
          id: "maths-nr-q13",
          type: "true-false",
          prompt: "Le produit de deux nombres négatifs est positif.",
          correct: true,
        },
        {
          id: "maths-nr-q14",
          type: "qcm",
          prompt: "(-15) ÷ (-3) = ?",
          options: ["-5", "-45", "5", "45"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q15",
          type: "fill-blank",
          prompt: "L'opposé de -12 est ___.",
          acceptedAnswers: ["12"],
        },
      ],
    },
    {
      id: "fractions",
      title: "Fractions",
      description: "Addition, multiplication, division et simplification",
      icon: "🍕",
      exercises: [
        { id: "maths-fr-q01", type: "qcm", prompt: "1/2 + 1/4 = ?", options: ["3/4", "2/6", "1/6", "2/4"], correctIndex: 0 },
        { id: "maths-fr-q02", type: "qcm", prompt: "2/3 × 3/4 = ?", options: ["1/2", "5/7", "6/7", "3/4"], correctIndex: 0 },
        { id: "maths-fr-q03", type: "fill-blank", prompt: "3/4 ÷ 1/2 = ___ (sous forme de fraction)", acceptedAnswers: ["3/2"] },
        { id: "maths-fr-q04", type: "qcm", prompt: "Simplifie 8/12.", options: ["2/3", "3/4", "1/2", "4/5"], correctIndex: 0 },
        { id: "maths-fr-q05", type: "true-false", prompt: "Pour additionner deux fractions, il faut qu'elles aient le même dénominateur.", correct: true },
        { id: "maths-fr-q06", type: "qcm", prompt: "5/6 - 1/3 = ?", options: ["1/2", "4/3", "1/3", "2/3"], correctIndex: 0 },
        { id: "maths-fr-q07", type: "fill-blank", prompt: "L'inverse de 2/5 est ___.", acceptedAnswers: ["5/2"] },
        { id: "maths-fr-q08", type: "qcm", prompt: "Quelle fraction est égale à 0,75 ?", options: ["3/4", "7/5", "3/5", "4/3"], correctIndex: 0 },
        { id: "maths-fr-q09", type: "true-false", prompt: "Pour diviser par une fraction, on multiplie par son inverse.", correct: true },
        { id: "maths-fr-q10", type: "qcm", prompt: "Quel dénominateur commun pour additionner 1/4 et 1/6 ?", options: ["12", "24", "10", "6"], correctIndex: 0 },
        { id: "maths-fr-q11", type: "fill-blank", prompt: "1/3 + 1/6 = ___ (fraction simplifiée)", acceptedAnswers: ["1/2"] },
        { id: "maths-fr-q12", type: "qcm", prompt: "(2/3)² = ?", options: ["4/9", "2/6", "4/6", "2/9"], correctIndex: 0 },
      ],
    },
    {
      id: "puissances",
      title: "Puissances",
      description: "Calculs et règles sur les puissances",
      icon: "⚡",
      exercises: [
        { id: "maths-pu-q01", type: "qcm", prompt: "2³ = ?", options: ["8", "6", "9", "4"], correctIndex: 0 },
        { id: "maths-pu-q02", type: "qcm", prompt: "10⁴ = ?", options: ["10000", "1000", "100000", "40"], correctIndex: 0 },
        { id: "maths-pu-q03", type: "fill-blank", prompt: "a³ × a² = a^___", acceptedAnswers: ["5"] },
        { id: "maths-pu-q04", type: "qcm", prompt: "a⁵ ÷ a² = ?", options: ["a³", "a⁷", "a²", "a¹⁰"], correctIndex: 0 },
        { id: "maths-pu-q05", type: "true-false", prompt: "Tout nombre élevé à la puissance 0 est égal à 1 (sauf 0).", correct: true },
        { id: "maths-pu-q06", type: "qcm", prompt: "(a³)² = ?", options: ["a⁶", "a⁵", "a⁹", "a¹"], correctIndex: 0 },
        { id: "maths-pu-q07", type: "fill-blank", prompt: "5⁻¹ = ___ (sous forme de fraction)", acceptedAnswers: ["1/5"] },
        { id: "maths-pu-q08", type: "qcm", prompt: "Quelle est la notation scientifique de 3 400 ?", options: ["3,4 × 10³", "34 × 10²", "3,4 × 10⁴", "0,34 × 10⁴"], correctIndex: 0 },
        { id: "maths-pu-q09", type: "true-false", prompt: "(-2)² = 4", correct: true },
        { id: "maths-pu-q10", type: "qcm", prompt: "(-2)³ = ?", options: ["-8", "8", "-6", "6"], correctIndex: 0 },
        { id: "maths-pu-q11", type: "fill-blank", prompt: "10⁻² = 0,___ (deux chiffres après la virgule)", acceptedAnswers: ["01"] },
        { id: "maths-pu-q12", type: "qcm", prompt: "a⁴ × a⁻² = ?", options: ["a²", "a⁶", "a⁻⁶", "a⁻²"], correctIndex: 0 },
      ],
    },
    {
      id: "calcul-litteral",
      title: "Calcul littéral",
      description: "Développer, factoriser et réduire des expressions",
      icon: "🔤",
      exercises: [
        { id: "maths-cl-q01", type: "qcm", prompt: "Développe 3(x + 2).", options: ["3x + 6", "3x + 2", "x + 6", "3x + 5"], correctIndex: 0 },
        { id: "maths-cl-q02", type: "qcm", prompt: "Développe -2(x - 5).", options: ["-2x + 10", "-2x - 10", "-2x + 5", "2x - 10"], correctIndex: 0 },
        { id: "maths-cl-q03", type: "fill-blank", prompt: "Factorise 4x + 8 : 4(___)", acceptedAnswers: ["x + 2", "x+2"] },
        { id: "maths-cl-q04", type: "qcm", prompt: "Réduis l'expression 3x + 5x - 2x.", options: ["6x", "8x", "10x", "4x"], correctIndex: 0 },
        { id: "maths-cl-q05", type: "true-false", prompt: "Dans l'expression 5x, 5 est le coefficient et x est la variable.", correct: true },
        { id: "maths-cl-q06", type: "qcm", prompt: "Calcule la valeur de 2x + 3 pour x = 4.", options: ["11", "9", "14", "7"], correctIndex: 0 },
        { id: "maths-cl-q07", type: "fill-blank", prompt: "Développe (x + 3)(x + 2) : x² + ___x + 6", acceptedAnswers: ["5"] },
        { id: "maths-cl-q08", type: "qcm", prompt: "Quelle est la forme développée de a(b + c) ?", options: ["ab + ac", "a + b + c", "abc", "ab × ac"], correctIndex: 0 },
        { id: "maths-cl-q09", type: "true-false", prompt: "On ne peut additionner que des termes de même nature (ex : x avec x, pas x avec x²).", correct: true },
        { id: "maths-cl-q10", type: "qcm", prompt: "Réduis : 2x² + 3x².", options: ["5x²", "5x⁴", "6x²", "5x"], correctIndex: 0 },
        { id: "maths-cl-q11", type: "fill-blank", prompt: "Factorise 6x - 9 : 3(___)", acceptedAnswers: ["2x - 3", "2x-3"] },
        { id: "maths-cl-q12", type: "qcm", prompt: "Développe -(x + 4).", options: ["-x - 4", "-x + 4", "x - 4", "x + 4"], correctIndex: 0 },
      ],
    },
    {
      id: "equations",
      title: "Équations",
      description: "Résoudre des équations du premier degré",
      icon: "⚖️",
      exercises: [
        { id: "maths-eq-q01", type: "qcm", prompt: "Résous x + 5 = 12.", options: ["x = 7", "x = 17", "x = -7", "x = 60"], correctIndex: 0 },
        { id: "maths-eq-q02", type: "qcm", prompt: "Résous 3x = 21.", options: ["x = 7", "x = 18", "x = 63", "x = 24"], correctIndex: 0 },
        { id: "maths-eq-q03", type: "fill-blank", prompt: "Résous 2x + 4 = 10 : x = ___", acceptedAnswers: ["3"] },
        { id: "maths-eq-q04", type: "true-false", prompt: "Pour résoudre une équation, on peut faire la même opération des deux côtés du signe =.", correct: true },
        { id: "maths-eq-q05", type: "qcm", prompt: "Résous x/3 = 5.", options: ["x = 15", "x = 8", "x = 2", "x = 5/3"], correctIndex: 0 },
        { id: "maths-eq-q06", type: "qcm", prompt: "Résous 5x - 3 = 2x + 9.", options: ["x = 4", "x = 2", "x = 6", "x = 12"], correctIndex: 0 },
        { id: "maths-eq-q07", type: "fill-blank", prompt: "Résous 7 - x = 2 : x = ___", acceptedAnswers: ["5"] },
        { id: "maths-eq-q08", type: "true-false", prompt: "L'équation 2x = 2x + 1 n'a pas de solution.", correct: true },
        { id: "maths-eq-q09", type: "qcm", prompt: "Quelle est la solution de x - 8 = -3 ?", options: ["x = 5", "x = -11", "x = 11", "x = -5"], correctIndex: 0 },
        { id: "maths-eq-q10", type: "qcm", prompt: "Résous 4(x + 1) = 20.", options: ["x = 4", "x = 5", "x = 19", "x = 6"], correctIndex: 0 },
        { id: "maths-eq-q11", type: "fill-blank", prompt: "Résous -3x = 9 : x = ___", acceptedAnswers: ["-3"] },
        { id: "maths-eq-q12", type: "true-false", prompt: "Vérifier une solution consiste à la remplacer dans l'équation initiale pour voir si l'égalité est vraie.", correct: true },
      ],
    },
    {
      id: "proportionnalite",
      title: "Proportionnalité",
      description: "Vitesses, échelles et pourcentages d'évolution",
      icon: "📊",
      exercises: [
        { id: "maths-pr-q01", type: "qcm", prompt: "Sur un plan à l'échelle 1/100, une distance de 5 cm représente en réalité :", options: ["5 m", "500 m", "50 m", "0,5 m"], correctIndex: 0 },
        { id: "maths-pr-q02", type: "qcm", prompt: "Un objet coûte 80€ et augmente de 25%. Quel est le nouveau prix ?", options: ["100€", "105€", "60€", "90€"], correctIndex: 0 },
        { id: "maths-pr-q03", type: "fill-blank", prompt: "Une voiture parcourt 150 km en 2h. Sa vitesse moyenne est de ___ km/h.", acceptedAnswers: ["75"] },
        { id: "maths-pr-q04", type: "true-false", prompt: "Deux grandeurs sont proportionnelles si l'une est obtenue en multipliant l'autre par un nombre constant.", correct: true },
        { id: "maths-pr-q05", type: "qcm", prompt: "Quel est le coefficient de proportionnalité entre 4 et 20 ?", options: ["5", "4", "16", "80"], correctIndex: 0 },
        { id: "maths-pr-q06", type: "qcm", prompt: "Un article à 50€ est soldé à -20%. Son nouveau prix est :", options: ["40€", "45€", "30€", "48€"], correctIndex: 0 },
        { id: "maths-pr-q07", type: "fill-blank", prompt: "Vitesse = distance ÷ ___", acceptedAnswers: ["temps"] },
        { id: "maths-pr-q08", type: "true-false", prompt: "Le tableau de proportionnalité permet de calculer une 4e valeur à partir de trois valeurs connues (produit en croix).", correct: true },
        { id: "maths-pr-q09", type: "qcm", prompt: "Une carte est à l'échelle 1/25000. Une distance de 4 cm sur la carte représente en réalité :", options: ["1 km", "100 m", "10 km", "400 m"], correctIndex: 0 },
        { id: "maths-pr-q10", type: "qcm", prompt: "Si 3 articles coûtent 12€, combien coûtent 7 articles ?", options: ["28€", "21€", "24€", "35€"], correctIndex: 0 },
        { id: "maths-pr-q11", type: "fill-blank", prompt: "Pour calculer un pourcentage d'évolution, on calcule (valeur finale − valeur initiale) ÷ ___ × 100.", acceptedAnswers: ["valeur initiale"] },
        { id: "maths-pr-q12", type: "qcm", prompt: "Une vitesse de 90 km/h correspond à environ :", options: ["25 m/s", "15 m/s", "50 m/s", "90 m/s"], correctIndex: 0 },
      ],
    },
    {
      id: "pythagore",
      title: "Théorème de Pythagore",
      description: "Calculer une longueur dans un triangle rectangle",
      icon: "📐",
      exercises: [
        { id: "maths-py-q01", type: "qcm", prompt: "Dans un triangle rectangle, le théorème de Pythagore relie :", options: ["les longueurs des trois côtés", "les angles", "les aires", "les périmètres"], correctIndex: 0 },
        { id: "maths-py-q02", type: "fill-blank", prompt: "Le théorème de Pythagore s'écrit : a² = b² + ___", acceptedAnswers: ["c²", "c^2"] },
        { id: "maths-py-q03", type: "qcm", prompt: "Un triangle rectangle a des côtés de 3 cm et 4 cm. Quelle est la longueur de l'hypoténuse ?", options: ["5 cm", "7 cm", "25 cm", "12 cm"], correctIndex: 0 },
        { id: "maths-py-q04", type: "true-false", prompt: "L'hypoténuse est le côté le plus long d'un triangle rectangle, opposé à l'angle droit.", correct: true },
        { id: "maths-py-q05", type: "qcm", prompt: "Un triangle a pour côtés 6, 8 et 10. Est-il rectangle ?", options: ["Oui, car 6² + 8² = 10²", "Non, les côtés sont trop grands", "Oui, car 10 est le plus grand", "Non, il manque des informations"], correctIndex: 0 },
        { id: "maths-py-q06", type: "fill-blank", prompt: "Si a² = b² + c², alors le triangle est ___ en A.", acceptedAnswers: ["rectangle"] },
        { id: "maths-py-q07", type: "qcm", prompt: "Un triangle rectangle a une hypoténuse de 13 cm et un côté de 5 cm. L'autre côté mesure :", options: ["12 cm", "18 cm", "8 cm", "144 cm"], correctIndex: 0 },
        { id: "maths-py-q08", type: "true-false", prompt: "On peut utiliser le théorème de Pythagore pour calculer un côté de n'importe quel triangle, même non rectangle.", correct: false, explanation: "Le théorème de Pythagore ne s'applique qu'aux triangles rectangles." },
        { id: "maths-py-q09", type: "qcm", prompt: "Quelle est la racine carrée de 49 ?", options: ["7", "14", "24,5", "9"], correctIndex: 0 },
        { id: "maths-py-q10", type: "qcm", prompt: "Si BC² ≠ AB² + AC², alors le triangle ABC :", options: ["n'est pas rectangle en A", "est rectangle en A", "est équilatéral", "n'existe pas"], correctIndex: 0 },
      ],
    },
    {
      id: "translations-symetrie",
      title: "Translations et symétrie centrale",
      description: "Transformations du plan et leurs propriétés",
      icon: "🔄",
      exercises: [
        { id: "maths-ts-q01", type: "qcm", prompt: "Une translation déplace une figure :", options: ["en suivant une direction, un sens et une distance", "en la faisant tourner", "en l'agrandissant", "sans la déplacer"], correctIndex: 0 },
        { id: "maths-ts-q02", type: "true-false", prompt: "Une translation conserve les longueurs et les angles d'une figure.", correct: true },
        { id: "maths-ts-q03", type: "qcm", prompt: "Le symétrique d'un point A par rapport à un point O est le point A' tel que :", options: ["O est le milieu de [AA']", "A' est très loin de A", "OA et OA' sont perpendiculaires", "A = A'"], correctIndex: 0 },
        { id: "maths-ts-q04", type: "fill-blank", prompt: "Dans une symétrie centrale de centre O, le point O est sa propre ___.", acceptedAnswers: ["image"] },
        { id: "maths-ts-q05", type: "true-false", prompt: "Une symétrie centrale conserve les longueurs, les angles et les aires.", correct: true },
        { id: "maths-ts-q06", type: "qcm", prompt: "L'image d'un segment par une translation est :", options: ["un segment de même longueur et parallèle", "un segment plus court", "un point", "un cercle"], correctIndex: 0 },
        { id: "maths-ts-q07", type: "qcm", prompt: "Pour construire l'image de A par la symétrie de centre O, on trace :", options: ["la droite (AO) et on place A' tel que O soit le milieu de [AA']", "un cercle de centre A", "une perpendiculaire à (AO) passant par O", "la médiatrice de [AO]"], correctIndex: 0 },
        { id: "maths-ts-q08", type: "true-false", prompt: "Le symétrique d'une droite par une symétrie centrale est une droite parallèle à la première.", correct: true },
        { id: "maths-ts-q09", type: "fill-blank", prompt: "Une translation est caractérisée par un vecteur qui indique la direction, le sens et la ___.", acceptedAnswers: ["distance", "longueur"] },
        { id: "maths-ts-q10", type: "qcm", prompt: "Le symétrique d'un cercle de rayon r par une symétrie centrale est :", options: ["un cercle de même rayon r", "un cercle de rayon différent", "une droite", "un point"], correctIndex: 0 },
      ],
    },
    {
      id: "statistiques",
      title: "Statistiques",
      description: "Moyenne, étendue, médiane et fréquences",
      icon: "📈",
      exercises: [
        { id: "maths-st-q01", type: "qcm", prompt: "Quelle est la moyenne des notes 12, 14, 16, 10 ?", options: ["13", "12", "14", "15"], correctIndex: 0 },
        { id: "maths-st-q02", type: "fill-blank", prompt: "L'étendue d'une série est la différence entre la valeur ___ et la valeur minimale.", acceptedAnswers: ["maximale", "maximum"] },
        { id: "maths-st-q03", type: "qcm", prompt: "Dans une série de 20 valeurs, l'effectif total est :", options: ["20", "1", "10", "dépend des valeurs"], correctIndex: 0 },
        { id: "maths-st-q04", type: "true-false", prompt: "La fréquence d'une valeur est égale à son effectif divisé par l'effectif total.", correct: true },
        { id: "maths-st-q05", type: "qcm", prompt: "Quelle est l'étendue de la série 5, 8, 3, 12, 7 ?", options: ["9", "12", "5", "7"], correctIndex: 0 },
        { id: "maths-st-q06", type: "fill-blank", prompt: "Pour calculer une moyenne pondérée, on multiplie chaque valeur par son ___ avant de sommer.", acceptedAnswers: ["effectif", "coefficient"] },
        { id: "maths-st-q07", type: "true-false", prompt: "La médiane d'une série partage les valeurs en deux groupes de même effectif.", correct: true },
        { id: "maths-st-q08", type: "qcm", prompt: "Quelle est la médiane de la série 3, 5, 7, 9, 11 ?", options: ["7", "5", "9", "6"], correctIndex: 0 },
        { id: "maths-st-q09", type: "qcm", prompt: "Une fréquence s'exprime souvent en :", options: ["pourcentage", "mètres", "degrés", "kilogrammes"], correctIndex: 0 },
        { id: "maths-st-q10", type: "true-false", prompt: "Un diagramme circulaire (camembert) est adapté pour représenter des fréquences.", correct: true },
      ],
    },
    {
      id: "aires-volumes",
      title: "Aires et volumes",
      description: "Calculs d'aires, de périmètres et de volumes usuels",
      icon: "📦",
      exercises: [
        { id: "maths-av-q01", type: "qcm", prompt: "Quelle est l'aire d'un rectangle de longueur 8 cm et largeur 5 cm ?", options: ["40 cm²", "26 cm²", "13 cm²", "80 cm²"], correctIndex: 0 },
        { id: "maths-av-q02", type: "fill-blank", prompt: "L'aire d'un disque de rayon r est A = π × ___", acceptedAnswers: ["r²", "r^2"] },
        { id: "maths-av-q03", type: "qcm", prompt: "Quel est le volume d'un cube d'arête 4 cm ?", options: ["64 cm³", "16 cm³", "48 cm³", "12 cm³"], correctIndex: 0 },
        { id: "maths-av-q04", type: "true-false", prompt: "Le volume d'un pavé droit est égal à longueur × largeur × hauteur.", correct: true },
        { id: "maths-av-q05", type: "qcm", prompt: "Quel est le volume approximatif d'un cylindre de rayon 3 cm et de hauteur 10 cm (π ≈ 3,14) ?", options: ["≈ 282,6 cm³", "≈ 94,2 cm³", "≈ 30 cm³", "≈ 188,4 cm³"], correctIndex: 0 },
        { id: "maths-av-q06", type: "fill-blank", prompt: "L'aire d'un triangle est A = (base × hauteur) ÷ ___", acceptedAnswers: ["2"] },
        { id: "maths-av-q07", type: "qcm", prompt: "Quelle unité convient pour exprimer un volume ?", options: ["cm³", "cm²", "cm", "km"], correctIndex: 0 },
        { id: "maths-av-q08", type: "true-false", prompt: "1 m³ = 1000 litres.", correct: true },
        { id: "maths-av-q09", type: "qcm", prompt: "Quel est le périmètre approximatif d'un cercle de rayon 5 cm (π ≈ 3,14) ?", options: ["≈ 31,4 cm", "≈ 15,7 cm", "≈ 78,5 cm", "≈ 10 cm"], correctIndex: 0 },
        { id: "maths-av-q10", type: "fill-blank", prompt: "Le volume d'un prisme droit est égal à l'aire de la base × ___", acceptedAnswers: ["hauteur"] },
      ],
    },
  ],
};
