import type { Subject } from "../types";

export const maths4eme: Subject = {
  id: "maths-4eme",
  name: "Maths",
  icon: "🔢",
  colorFrom: "from-blue-500",
  colorTo: "to-indigo-600",
  chapters: [
    {
      id: "nombres-relatifs",
      title: "Nombres relatifs",
      description: "Addition, soustraction, multiplication, division",
      icon: "➖",
      exercises: [
        {
          id: "maths-nr-q01",
          type: "qcm",
          prompt: "(-5) + 3 = ?",
          options: ["-8", "-2", "2", "8"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q02",
          type: "qcm",
          prompt: "7 + (-10) = ?",
          options: ["-17", "-3", "3", "17"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q03",
          type: "qcm",
          prompt: "(-4) - (-6) = ?",
          options: ["-10", "-2", "2", "10"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q04",
          type: "qcm",
          prompt: "(-3) × 5 = ?",
          options: ["-15", "-8", "8", "15"],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q05",
          type: "qcm",
          prompt: "(-6) × (-2) = ?",
          options: ["-12", "-4", "4", "12"],
          correctIndex: 3,
        },
        {
          id: "maths-nr-q06",
          type: "qcm",
          prompt: "(-12) ÷ 4 = ?",
          options: ["-8", "-3", "3", "8"],
          correctIndex: 1,
        },
        {
          id: "maths-nr-q07",
          type: "true-false",
          prompt: "-8 est plus petit que -3.",
          correct: true,
          explanation: "Sur la droite numérique, plus on va vers la gauche, plus le nombre est petit. -8 est plus à gauche que -3.",
        },
        {
          id: "maths-nr-q08",
          type: "qcm",
          prompt: "Quelle est la valeur absolue de -7 ?",
          options: ["-7", "0", "7", "14"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q09",
          type: "fill-blank",
          prompt: "Le résultat de (-9) + 9 est ___.",
          acceptedAnswers: ["0"],
        },
        {
          id: "maths-nr-q10",
          type: "qcm",
          prompt: "(-2) × (-3) × (-1) = ?",
          options: ["-6", "-1", "1", "6"],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q11",
          type: "qcm",
          prompt: "Range -5 ; 2 ; -1 ; 0 dans l'ordre croissant.",
          options: [
            "-5 < -1 < 0 < 2",
            "-1 < -5 < 0 < 2",
            "2 < 0 < -1 < -5",
            "0 < -1 < -5 < 2",
          ],
          correctIndex: 0,
        },
        {
          id: "maths-nr-q12",
          type: "qcm",
          prompt: "5 - (-3) = ?",
          options: ["2", "-2", "8", "-8"],
          correctIndex: 2,
          explanation: "Soustraire un nombre négatif équivaut à ajouter son opposé : 5 - (-3) = 5 + 3 = 8.",
        },
        {
          id: "maths-nr-q13",
          type: "true-false",
          prompt: "Le produit de deux nombres négatifs est positif.",
          correct: true,
        },
        {
          id: "maths-nr-q14",
          type: "qcm",
          prompt: "(-15) ÷ (-3) = ?",
          options: ["-5", "-45", "5", "45"],
          correctIndex: 2,
        },
        {
          id: "maths-nr-q15",
          type: "fill-blank",
          prompt: "L'opposé de -12 est ___.",
          acceptedAnswers: ["12"],
        },
      ],
    },
  ],
};
