import type { Subject } from "../types";

export const physiqueChimie: Subject = {
  id: "physique-chimie",
  name: "Physique-Chimie",
  icon: "⚗️",
  colorFrom: "from-violet-600",
  colorTo: "to-indigo-800",
  chapters: [
    {
      id: "revision-5eme-matiere",
      title: "Révision 5ème : états et mélanges",
      description: "États de la matière, changements d'état, mélanges",
      icon: "💧",
      exercises: [
        {
          id: "pc-r5-q01",
          type: "qcm",
          prompt: "Quel est l'état physique de l'eau à 20°C sous pression atmosphérique normale ?",
          options: ["Liquide", "Solide", "Gazeux", "Plasma"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q02",
          type: "true-false",
          prompt: "Un corps pur est constitué d'une seule sorte de molécules.",
          correct: true,
        },
        {
          id: "pc-r5-q03",
          type: "qcm",
          prompt: "Un mélange homogène est un mélange où...",
          options: [
            "on ne distingue pas les différents constituants à l'œil",
            "on voit clairement les différents constituants",
            "il n'y a qu'un seul constituant",
            "il n'existe pas en chimie",
          ],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q04",
          type: "fill-blank",
          prompt: "Le changement d'état de liquide à gazeux s'appelle la ___.",
          acceptedAnswers: ["vaporisation"],
        },
        {
          id: "pc-r5-q05",
          type: "fill-blank",
          prompt: "Le changement d'état de gazeux à liquide s'appelle la ___.",
          acceptedAnswers: ["condensation", "liquéfaction"],
        },
        {
          id: "pc-r5-q06",
          type: "qcm",
          prompt: "Quelle est la température de fusion de l'eau pure (à pression normale) ?",
          options: ["0°C", "100°C", "37°C", "-10°C"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q07",
          type: "qcm",
          prompt: "Quelle est la température d'ébullition de l'eau pure (à pression normale) ?",
          options: ["100°C", "0°C", "50°C", "212°C"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q08",
          type: "true-false",
          prompt: "On peut séparer les constituants d'un mélange par filtration ou distillation.",
          correct: true,
        },
        {
          id: "pc-r5-q09",
          type: "qcm",
          prompt: "Quel instrument utilise-t-on pour mesurer une masse ?",
          options: ["Une balance", "Un thermomètre", "Un chronomètre", "Un voltmètre"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q10",
          type: "true-false",
          prompt: "La masse d'un objet se conserve lors d'un changement d'état.",
          correct: true,
        },
      ],
    },
    {
      id: "electricite",
      title: "Électricité : tension et intensité",
      description: "Lois des circuits, loi d'Ohm, conducteurs et isolants (4ème)",
      icon: "⚡",
      exercises: [
        {
          id: "pc-elec-q01",
          type: "qcm",
          prompt: "Quelle unité mesure l'intensité du courant électrique ?",
          options: ["L'ampère (A)", "Le volt (V)", "Le watt (W)", "L'ohm (Ω)"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q02",
          type: "qcm",
          prompt: "Quelle unité mesure la tension électrique ?",
          options: ["Le volt (V)", "L'ampère (A)", "Le watt (W)", "L'ohm (Ω)"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q03",
          type: "true-false",
          prompt: "Dans un circuit en série, l'intensité est la même en tout point du circuit.",
          correct: true,
        },
        {
          id: "pc-elec-q04",
          type: "true-false",
          prompt: "Dans un circuit en dérivation (parallèle), la tension est la même aux bornes de chaque branche.",
          correct: true,
        },
        {
          id: "pc-elec-q05",
          type: "qcm",
          prompt: "Quel appareil mesure l'intensité d'un courant ?",
          options: ["Un ampèremètre", "Un voltmètre", "Un thermomètre", "Un baromètre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q06",
          type: "qcm",
          prompt: "Quel appareil mesure la tension électrique ?",
          options: ["Un voltmètre", "Un ampèremètre", "Un manomètre", "Un altimètre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q07",
          type: "fill-blank",
          prompt: "La loi d'Ohm relie la tension U, l'intensité I et la ___ R d'un conducteur.",
          acceptedAnswers: ["résistance"],
        },
        {
          id: "pc-elec-q08",
          type: "qcm",
          prompt: "Que vaut la formule de la loi d'Ohm ?",
          options: ["U = R × I", "U = R / I", "U = R + I", "I = U + R"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q09",
          type: "true-false",
          prompt: "Un ampèremètre se branche en série dans le circuit.",
          correct: true,
        },
        {
          id: "pc-elec-q10",
          type: "true-false",
          prompt: "Un voltmètre se branche en dérivation (en parallèle) aux bornes du composant.",
          correct: true,
        },
        {
          id: "pc-elec-q11",
          type: "qcm",
          prompt: "Quel matériau est un bon conducteur électrique ?",
          options: ["Le cuivre", "Le bois", "Le plastique", "Le verre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q12",
          type: "qcm",
          prompt: "Quel matériau est un isolant électrique ?",
          options: ["Le plastique", "Le cuivre", "L'aluminium", "Le fer"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q13",
          type: "fill-blank",
          prompt: "Un composant qui s'oppose au passage du courant s'appelle une ___.",
          acceptedAnswers: ["résistance"],
        },
        {
          id: "pc-elec-q14",
          type: "true-false",
          prompt: "Un court-circuit peut être dangereux car il fait circuler une intensité très élevée.",
          correct: true,
        },
        {
          id: "pc-elec-q15",
          type: "qcm",
          prompt: "Que produit une pile dans un circuit électrique ?",
          options: ["Une tension électrique", "De la lumière directement", "Un son", "Une masse"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "lumiere-vision",
      title: "Lumière et vision",
      description: "Propagation de la lumière, sources et objets diffusants",
      icon: "💡",
      exercises: [
        { id: "pc-lum-q01", type: "qcm", prompt: "Dans le vide, la lumière se propage en ligne :", options: ["droite", "courbe", "ondulée", "aléatoire"], correctIndex: 0 },
        { id: "pc-lum-q02", type: "qcm", prompt: "Quelle est la vitesse de la lumière dans le vide (environ) ?", options: ["300 000 km/s", "300 km/s", "3 000 km/s", "30 000 km/s"], correctIndex: 0 },
        { id: "pc-lum-q03", type: "true-false", prompt: "Un objet lumineux produit sa propre lumière (ex : le Soleil, une ampoule).", correct: true },
        { id: "pc-lum-q04", type: "fill-blank", prompt: "Un objet qui ne produit pas sa propre lumière mais qui réfléchit la lumière reçue est un objet ___.", acceptedAnswers: ["diffusant", "éclairé"] },
        { id: "pc-lum-q05", type: "qcm", prompt: "Pour voir un objet, il faut que la lumière de cet objet atteigne :", options: ["nos yeux", "le soleil", "l'objet lui-même", "rien de particulier"], correctIndex: 0 },
        { id: "pc-lum-q06", type: "true-false", prompt: "La Lune est un objet lumineux qui produit sa propre lumière.", correct: false, explanation: "La Lune est un objet diffusant : elle réfléchit la lumière du Soleil." },
        { id: "pc-lum-q07", type: "qcm", prompt: "Quel phénomène se produit quand la lumière traverse un milieu transparent différent (ex : l'eau) ?", options: ["la réfraction", "l'absorption totale", "la disparition", "l'évaporation"], correctIndex: 0 },
        { id: "pc-lum-q08", type: "fill-blank", prompt: "Une éclipse de Soleil se produit quand la ___ passe entre la Terre et le Soleil.", acceptedAnswers: ["lune", "Lune"] },
        { id: "pc-lum-q09", type: "true-false", prompt: "La lumière met environ 8 minutes pour parcourir la distance du Soleil à la Terre.", correct: true },
        { id: "pc-lum-q10", type: "qcm", prompt: "Quel instrument permet de dévier la lumière pour former une image (ex : dans un appareil photo) ?", options: ["une lentille", "un thermomètre", "une balance", "un ampèremètre"], correctIndex: 0 },
      ],
    },
    {
      id: "mouvement-vitesse",
      title: "Mouvement et vitesse",
      description: "Référentiel, trajectoire et calcul de vitesse",
      icon: "🏎️",
      exercises: [
        { id: "pc-mv-q01", type: "qcm", prompt: "La vitesse moyenne se calcule par la formule :", options: ["distance ÷ temps", "temps ÷ distance", "distance × temps", "distance + temps"], correctIndex: 0 },
        { id: "pc-mv-q02", type: "fill-blank", prompt: "Un objet immobile par rapport à un référentiel donné est dit ___ par rapport à ce référentiel.", acceptedAnswers: ["immobile", "fixe", "au repos"] },
        { id: "pc-mv-q03", type: "true-false", prompt: "Le mouvement d'un objet dépend du référentiel choisi pour l'observer.", correct: true },
        { id: "pc-mv-q04", type: "qcm", prompt: "Une voiture parcourt 120 km en 1h30. Quelle est sa vitesse moyenne ?", options: ["80 km/h", "120 km/h", "90 km/h", "60 km/h"], correctIndex: 0 },
        { id: "pc-mv-q05", type: "qcm", prompt: "Quelle unité de vitesse est l'unité internationale en physique ?", options: ["m/s", "km/h", "m/h", "km/s"], correctIndex: 0 },
        { id: "pc-mv-q06", type: "true-false", prompt: "Plus la vitesse d'un objet est grande, plus il parcourt de distance en un temps donné.", correct: true },
        { id: "pc-mv-q07", type: "qcm", prompt: "Un mouvement est dit rectiligne lorsque :", options: ["la trajectoire est une droite", "la vitesse est constante", "l'objet est immobile", "la trajectoire est un cercle"], correctIndex: 0 },
        { id: "pc-mv-q08", type: "qcm", prompt: "Un mouvement est dit uniforme lorsque :", options: ["la vitesse est constante", "la trajectoire est droite", "l'objet accélère", "l'objet recule"], correctIndex: 0 },
        { id: "pc-mv-q09", type: "fill-blank", prompt: "La trajectoire d'un objet est l'ensemble des positions qu'il occupe au cours du ___.", acceptedAnswers: ["temps", "mouvement"] },
        { id: "pc-mv-q10", type: "true-false", prompt: "1 km/h correspond à un peu moins de 0,3 m/s.", correct: true },
      ],
    },
    {
      id: "energie-transferts",
      title: "Énergie et ses transferts",
      description: "Formes d'énergie, transformations et transferts thermiques",
      icon: "🔋",
      exercises: [
        { id: "pc-en-q01", type: "qcm", prompt: "Laquelle de ces sources d'énergie est renouvelable ?", options: ["le soleil", "le pétrole", "le charbon", "le gaz naturel"], correctIndex: 0 },
        { id: "pc-en-q02", type: "true-false", prompt: "L'énergie ne peut ni être créée ni disparaître, elle se transforme ou se transfère.", correct: true },
        { id: "pc-en-q03", type: "qcm", prompt: "Quelle forme d'énergie possède un objet en mouvement ?", options: ["énergie cinétique", "énergie chimique", "énergie nucléaire", "énergie lumineuse"], correctIndex: 0 },
        { id: "pc-en-q04", type: "fill-blank", prompt: "L'énergie stockée dans un objet en hauteur s'appelle l'énergie potentielle de ___.", acceptedAnswers: ["pesanteur", "position"] },
        { id: "pc-en-q05", type: "qcm", prompt: "Un panneau solaire transforme l'énergie lumineuse en énergie :", options: ["électrique", "mécanique", "chimique", "nucléaire"], correctIndex: 0 },
        { id: "pc-en-q06", type: "true-false", prompt: "La combustion du bois libère de l'énergie thermique.", correct: true },
        { id: "pc-en-q07", type: "qcm", prompt: "Quelle unité mesure une quantité d'énergie ?", options: ["le joule (J)", "le mètre (m)", "le watt (W) uniquement", "le volt (V)"], correctIndex: 0 },
        { id: "pc-en-q08", type: "fill-blank", prompt: "La chaleur se transmet des zones ___ vers les zones plus froides.", acceptedAnswers: ["chaudes"] },
        { id: "pc-en-q09", type: "true-false", prompt: "Un isolant thermique limite les transferts de chaleur.", correct: true },
        { id: "pc-en-q10", type: "qcm", prompt: "Quel appareil transforme l'énergie électrique en énergie mécanique ?", options: ["un moteur électrique", "une pile", "un panneau solaire", "un thermomètre"], correctIndex: 0 },
      ],
    },
    {
      id: "atomes-molecules",
      title: "Atomes et molécules",
      description: "Constitution de la matière et transformations chimiques",
      icon: "⚛️",
      exercises: [
        { id: "pc-am-q01", type: "qcm", prompt: "Quelle est la plus petite particule de matière qui caractérise un élément chimique ?", options: ["l'atome", "la molécule", "le neutron", "l'électron"], correctIndex: 0 },
        { id: "pc-am-q02", type: "true-false", prompt: "Une molécule est un assemblage de plusieurs atomes liés entre eux.", correct: true },
        { id: "pc-am-q03", type: "qcm", prompt: "Quelle est la formule chimique de l'eau ?", options: ["H2O", "CO2", "O2", "H2"], correctIndex: 0 },
        { id: "pc-am-q04", type: "fill-blank", prompt: "L'air est principalement composé de diazote et de ___.", acceptedAnswers: ["dioxygène", "oxygène"] },
        { id: "pc-am-q05", type: "qcm", prompt: "Combien d'atomes d'oxygène contient une molécule de dioxyde de carbone (CO2) ?", options: ["2", "1", "3", "0"], correctIndex: 0 },
        { id: "pc-am-q06", type: "true-false", prompt: "Lors d'une transformation chimique, les atomes se réarrangent mais ne disparaissent pas.", correct: true },
        { id: "pc-am-q07", type: "qcm", prompt: "Quel est le symbole chimique du carbone ?", options: ["C", "Ca", "Co", "Cl"], correctIndex: 0 },
        { id: "pc-am-q08", type: "fill-blank", prompt: "Une réaction de combustion nécessite un combustible et un ___.", acceptedAnswers: ["comburant"] },
        { id: "pc-am-q09", type: "true-false", prompt: "Le dioxygène est le comburant le plus courant dans les combustions.", correct: true },
        { id: "pc-am-q10", type: "qcm", prompt: "Quel symbole représente l'élément hydrogène ?", options: ["H", "He", "Hy", "Hg"], correctIndex: 0 },
      ],
    },
  ],
};
