import type { Subject } from "../types";

export const physiqueChimie: Subject = {
  id: "physique-chimie",
  name: "Physique-Chimie",
  icon: "⚗️",
  colorFrom: "from-violet-600",
  colorTo: "to-indigo-800",
  chapters: [
    {
      id: "revision-5eme-matiere",
      title: "Révision 5ème : états et mélanges",
      description: "États de la matière, changements d'état, mélanges",
      icon: "💧",
      exercises: [
        {
          id: "pc-r5-q01",
          type: "qcm",
          prompt: "Quel est l'état physique de l'eau à 20°C sous pression atmosphérique normale ?",
          options: ["Liquide", "Solide", "Gazeux", "Plasma"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q02",
          type: "true-false",
          prompt: "Un corps pur est constitué d'une seule sorte de molécules.",
          correct: true,
        },
        {
          id: "pc-r5-q03",
          type: "qcm",
          prompt: "Un mélange homogène est un mélange où...",
          options: [
            "on ne distingue pas les différents constituants à l'œil",
            "on voit clairement les différents constituants",
            "il n'y a qu'un seul constituant",
            "il n'existe pas en chimie",
          ],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q04",
          type: "fill-blank",
          prompt: "Le changement d'état de liquide à gazeux s'appelle la ___.",
          acceptedAnswers: ["vaporisation"],
        },
        {
          id: "pc-r5-q05",
          type: "fill-blank",
          prompt: "Le changement d'état de gazeux à liquide s'appelle la ___.",
          acceptedAnswers: ["condensation", "liquéfaction"],
        },
        {
          id: "pc-r5-q06",
          type: "qcm",
          prompt: "Quelle est la température de fusion de l'eau pure (à pression normale) ?",
          options: ["0°C", "100°C", "37°C", "-10°C"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q07",
          type: "qcm",
          prompt: "Quelle est la température d'ébullition de l'eau pure (à pression normale) ?",
          options: ["100°C", "0°C", "50°C", "212°C"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q08",
          type: "true-false",
          prompt: "On peut séparer les constituants d'un mélange par filtration ou distillation.",
          correct: true,
        },
        {
          id: "pc-r5-q09",
          type: "qcm",
          prompt: "Quel instrument utilise-t-on pour mesurer une masse ?",
          options: ["Une balance", "Un thermomètre", "Un chronomètre", "Un voltmètre"],
          correctIndex: 0,
        },
        {
          id: "pc-r5-q10",
          type: "true-false",
          prompt: "La masse d'un objet se conserve lors d'un changement d'état.",
          correct: true,
        },
      ],
    },
    {
      id: "electricite",
      title: "Électricité : tension et intensité",
      description: "Lois des circuits, loi d'Ohm, conducteurs et isolants (4ème)",
      icon: "⚡",
      exercises: [
        {
          id: "pc-elec-q01",
          type: "qcm",
          prompt: "Quelle unité mesure l'intensité du courant électrique ?",
          options: ["L'ampère (A)", "Le volt (V)", "Le watt (W)", "L'ohm (Ω)"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q02",
          type: "qcm",
          prompt: "Quelle unité mesure la tension électrique ?",
          options: ["Le volt (V)", "L'ampère (A)", "Le watt (W)", "L'ohm (Ω)"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q03",
          type: "true-false",
          prompt: "Dans un circuit en série, l'intensité est la même en tout point du circuit.",
          correct: true,
        },
        {
          id: "pc-elec-q04",
          type: "true-false",
          prompt: "Dans un circuit en dérivation (parallèle), la tension est la même aux bornes de chaque branche.",
          correct: true,
        },
        {
          id: "pc-elec-q05",
          type: "qcm",
          prompt: "Quel appareil mesure l'intensité d'un courant ?",
          options: ["Un ampèremètre", "Un voltmètre", "Un thermomètre", "Un baromètre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q06",
          type: "qcm",
          prompt: "Quel appareil mesure la tension électrique ?",
          options: ["Un voltmètre", "Un ampèremètre", "Un manomètre", "Un altimètre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q07",
          type: "fill-blank",
          prompt: "La loi d'Ohm relie la tension U, l'intensité I et la ___ R d'un conducteur.",
          acceptedAnswers: ["résistance"],
        },
        {
          id: "pc-elec-q08",
          type: "qcm",
          prompt: "Que vaut la formule de la loi d'Ohm ?",
          options: ["U = R × I", "U = R / I", "U = R + I", "I = U + R"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q09",
          type: "true-false",
          prompt: "Un ampèremètre se branche en série dans le circuit.",
          correct: true,
        },
        {
          id: "pc-elec-q10",
          type: "true-false",
          prompt: "Un voltmètre se branche en dérivation (en parallèle) aux bornes du composant.",
          correct: true,
        },
        {
          id: "pc-elec-q11",
          type: "qcm",
          prompt: "Quel matériau est un bon conducteur électrique ?",
          options: ["Le cuivre", "Le bois", "Le plastique", "Le verre"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q12",
          type: "qcm",
          prompt: "Quel matériau est un isolant électrique ?",
          options: ["Le plastique", "Le cuivre", "L'aluminium", "Le fer"],
          correctIndex: 0,
        },
        {
          id: "pc-elec-q13",
          type: "fill-blank",
          prompt: "Un composant qui s'oppose au passage du courant s'appelle une ___.",
          acceptedAnswers: ["résistance"],
        },
        {
          id: "pc-elec-q14",
          type: "true-false",
          prompt: "Un court-circuit peut être dangereux car il fait circuler une intensité très élevée.",
          correct: true,
        },
        {
          id: "pc-elec-q15",
          type: "qcm",
          prompt: "Que produit une pile dans un circuit électrique ?",
          options: ["Une tension électrique", "De la lumière directement", "Un son", "Une masse"],
          correctIndex: 0,
        },
      ],
    },
  ],
};
