import type { Subject } from "../types";

export const svt: Subject = {
  id: "svt",
  name: "SVT",
  icon: "🧬",
  colorFrom: "from-lime-500",
  colorTo: "to-green-600",
  chapters: [
    {
      id: "revision-5eme-respiration",
      title: "Révision 5ème : respiration et milieux",
      description: "Échanges gazeux et peuplement des milieux de vie",
      icon: "🌿",
      exercises: [
        {
          id: "svt-r5-q01",
          type: "qcm",
          prompt: "Où les poissons trouvent-ils le dioxygène nécessaire à leur respiration ?",
          options: ["Dans l'eau", "Dans l'air uniquement", "Dans la terre", "Ils n'en ont pas besoin"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q02",
          type: "true-false",
          prompt: "Les organes respiratoires permettent les échanges gazeux entre l'organisme et son milieu.",
          correct: true,
        },
        {
          id: "svt-r5-q03",
          type: "qcm",
          prompt: "Quel organe respiratoire utilisent les poissons ?",
          options: ["Les branchies", "Les poumons", "La trachée", "La peau uniquement"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q04",
          type: "qcm",
          prompt: "Quel organe respiratoire utilisent les mammifères ?",
          options: ["Les poumons", "Les branchies", "Les trachées", "Les stomates"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q05",
          type: "fill-blank",
          prompt: "Le ___ est le gaz indispensable à la respiration, prélevé dans le milieu de vie.",
          acceptedAnswers: ["dioxygène", "oxygène"],
        },
        {
          id: "svt-r5-q06",
          type: "true-false",
          prompt: "La répartition des êtres vivants dans un milieu dépend des conditions de vie (température, eau, lumière...).",
          correct: true,
        },
        {
          id: "svt-r5-q07",
          type: "qcm",
          prompt: "Quel facteur peut limiter la présence d'un être vivant dans un milieu ?",
          options: [
            "Le manque de nourriture ou d'eau",
            "La couleur du ciel",
            "Le bruit uniquement",
            "Aucun facteur ne limite la présence",
          ],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q08",
          type: "fill-blank",
          prompt: "Un ensemble d'êtres vivants et de leur milieu de vie qui interagissent forme un ___.",
          acceptedAnswers: ["écosystème"],
        },
        {
          id: "svt-r5-q09",
          type: "qcm",
          prompt: "Comment les insectes respirent-ils généralement ?",
          options: ["Par des trachées", "Par des branchies", "Par des poumons", "Par la peau uniquement"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q10",
          type: "true-false",
          prompt: "Le peuplement d'un milieu peut changer au cours des saisons.",
          correct: true,
        },
      ],
    },
    {
      id: "reproduction-heredite",
      title: "Reproduction et hérédité",
      description: "Fécondation, chromosomes et caractères héréditaires (4ème)",
      icon: "🧬",
      exercises: [
        {
          id: "svt-rh-q01",
          type: "qcm",
          prompt: "Quel est le rôle des spermatozoïdes ?",
          options: ["Féconder l'ovule", "Produire du lait", "Digérer les aliments", "Filtrer le sang"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q02",
          type: "true-false",
          prompt: "La fécondation a lieu dans l'utérus.",
          correct: false,
          explanation: "La fécondation a lieu dans les trompes (oviductes) ; l'embryon se développe ensuite dans l'utérus.",
        },
        {
          id: "svt-rh-q03",
          type: "qcm",
          prompt: "Combien de chromosomes possède une cellule humaine normale ?",
          options: ["23", "46", "92", "12"],
          correctIndex: 1,
        },
        {
          id: "svt-rh-q04",
          type: "fill-blank",
          prompt: "Le brassage des chromosomes lors de la formation des cellules reproductrices est appelé la ___.",
          acceptedAnswers: ["meiose", "méiose"],
        },
        {
          id: "svt-rh-q05",
          type: "qcm",
          prompt: "Qu'est-ce qu'un caractère héréditaire ?",
          options: [
            "Un trait transmis des parents aux enfants",
            "Une maladie contagieuse",
            "Un comportement appris",
            "Un trait acquis pendant la vie",
          ],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q06",
          type: "true-false",
          prompt: "Les jumeaux identiques (vrais jumeaux) ont exactement le même ADN.",
          correct: true,
        },
        {
          id: "svt-rh-q07",
          type: "qcm",
          prompt: "Où se déroule la fécondation chez les mammifères ?",
          options: ["Dans les trompes (oviductes)", "Dans l'utérus", "Dans les ovaires", "Dans le vagin"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q08",
          type: "fill-blank",
          prompt: "Les chromosomes sont situés dans le ___ de la cellule.",
          acceptedAnswers: ["noyau"],
        },
        {
          id: "svt-rh-q09",
          type: "qcm",
          prompt: "Qu'apporte le spermatozoïde lors de la fécondation ?",
          options: ["23 chromosomes", "46 chromosomes", "De la nourriture", "Rien"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q10",
          type: "true-false",
          prompt: "Un gène peut exister sous plusieurs versions appelées allèles.",
          correct: true,
        },
        {
          id: "svt-rh-q11",
          type: "qcm",
          prompt: "Quel organe produit les spermatozoïdes ?",
          options: ["Les testicules", "Les ovaires", "Le pancréas", "Le foie"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q12",
          type: "qcm",
          prompt: "Quel organe produit les ovules ?",
          options: ["Les ovaires", "Les testicules", "L'utérus", "Le vagin"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q13",
          type: "fill-blank",
          prompt: "L'organe où se développe l'embryon puis le fœtus est l'___.",
          acceptedAnswers: ["utérus"],
        },
        {
          id: "svt-rh-q14",
          type: "true-false",
          prompt: "Le caryotype humain est composé de 23 paires de chromosomes.",
          correct: true,
        },
        {
          id: "svt-rh-q15",
          type: "qcm",
          prompt: "Quelle structure relie le fœtus au placenta ?",
          options: ["Le cordon ombilical", "La trompe", "L'oviducte", "L'urètre"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "systeme-nerveux",
      title: "Système nerveux et comportements",
      description: "Cerveau, neurones, réflexes et comportements responsables",
      icon: "🧠",
      exercises: [
        { id: "svt-sn-q01", type: "qcm", prompt: "Quel organe coordonne les informations reçues par le corps ?", options: ["Le cerveau", "Le cœur", "Le foie", "L'estomac"], correctIndex: 0 },
        { id: "svt-sn-q02", type: "true-false", prompt: "Le système nerveux est composé du cerveau, de la moelle épinière et des nerfs.", correct: true },
        { id: "svt-sn-q03", type: "qcm", prompt: "Quel type de cellule transmet les messages nerveux ?", options: ["Le neurone", "Le globule rouge", "Le globule blanc", "La cellule musculaire"], correctIndex: 0 },
        { id: "svt-sn-q04", type: "fill-blank", prompt: "Un comportement involontaire et rapide en réponse à un stimulus s'appelle un ___.", acceptedAnswers: ["réflexe"] },
        { id: "svt-sn-q05", type: "true-false", prompt: "La consommation d'alcool ou de drogues peut perturber le fonctionnement du système nerveux.", correct: true },
        { id: "svt-sn-q06", type: "qcm", prompt: "Quel organe des sens permet de percevoir la lumière ?", options: ["L'œil", "L'oreille", "Le nez", "La langue"], correctIndex: 0 },
        { id: "svt-sn-q07", type: "qcm", prompt: "Quel est le rôle des nerfs ?", options: ["Transmettre les messages nerveux entre le cerveau et le corps", "Produire des hormones", "Filtrer le sang", "Digérer les aliments"], correctIndex: 0 },
        { id: "svt-sn-q08", type: "true-false", prompt: "Le sommeil est essentiel au bon fonctionnement du cerveau.", correct: true },
        { id: "svt-sn-q09", type: "fill-blank", prompt: "La moelle épinière est protégée par la colonne ___.", acceptedAnswers: ["vertébrale"] },
        { id: "svt-sn-q10", type: "qcm", prompt: "Quelle substance peut perturber gravement le fonctionnement du cerveau ?", options: ["L'alcool", "L'eau", "Les vitamines", "Les protéines"], correctIndex: 0 },
      ],
    },
    {
      id: "risque-infectieux-immunite",
      title: "Risque infectieux et immunité",
      description: "Micro-organismes, défenses de l'organisme et vaccination",
      icon: "🦠",
      exercises: [
        { id: "svt-ri-q01", type: "qcm", prompt: "Qu'est-ce qu'un micro-organisme pathogène ?", options: ["Un micro-organisme qui peut provoquer une maladie", "Un micro-organisme toujours utile", "Une cellule du corps humain", "Un médicament"], correctIndex: 0 },
        { id: "svt-ri-q02", type: "true-false", prompt: "Les bactéries et les virus peuvent tous deux provoquer des infections.", correct: true },
        { id: "svt-ri-q03", type: "qcm", prompt: "Quel est le rôle des globules blancs ?", options: ["Défendre l'organisme contre les infections", "Transporter le dioxygène", "Transporter les nutriments", "Produire de l'énergie"], correctIndex: 0 },
        { id: "svt-ri-q04", type: "fill-blank", prompt: "Un vaccin permet de préparer le système ___ à se défendre contre un agent infectieux.", acceptedAnswers: ["immunitaire"] },
        { id: "svt-ri-q05", type: "true-false", prompt: "Se laver les mains régulièrement limite la transmission de micro-organismes pathogènes.", correct: true },
        { id: "svt-ri-q06", type: "qcm", prompt: "Quel est le rôle des anticorps ?", options: ["Reconnaître et neutraliser un agent infectieux spécifique", "Transporter l'oxygène", "Digérer les aliments", "Produire de l'énergie"], correctIndex: 0 },
        { id: "svt-ri-q07", type: "true-false", prompt: "Un antibiotique est efficace contre les virus.", correct: false, explanation: "Les antibiotiques agissent contre les bactéries, pas contre les virus." },
        { id: "svt-ri-q08", type: "fill-blank", prompt: "La peau et les muqueuses forment une première ___ contre les infections.", acceptedAnswers: ["barrière", "protection"] },
        { id: "svt-ri-q09", type: "qcm", prompt: "Comment une maladie infectieuse peut-elle se transmettre ?", options: ["Par contact, par l'air ou par l'eau", "Uniquement par contact", "Uniquement par l'air", "Elle ne se transmet jamais"], correctIndex: 0 },
        { id: "svt-ri-q10", type: "true-false", prompt: "Après une vaccination, le corps garde en mémoire la façon de se défendre contre l'agent infectieux.", correct: true },
      ],
    },
    {
      id: "activite-interne-globe",
      title: "Activité interne du globe",
      description: "Séismes, volcans et plaques tectoniques",
      icon: "🌋",
      exercises: [
        { id: "svt-ag-q01", type: "qcm", prompt: "Qu'est-ce qu'un séisme ?", options: ["Une vibration brutale du sol", "Une éruption volcanique", "Une inondation", "Un changement climatique"], correctIndex: 0 },
        { id: "svt-ag-q02", type: "true-false", prompt: "Les séismes se produisent souvent aux limites des plaques tectoniques.", correct: true },
        { id: "svt-ag-q03", type: "qcm", prompt: "Quel instrument mesure les vibrations d'un séisme ?", options: ["Un sismographe", "Un thermomètre", "Un baromètre", "Un altimètre"], correctIndex: 0 },
        { id: "svt-ag-q04", type: "fill-blank", prompt: "La Terre est découpée en plusieurs grandes ___ qui se déplacent lentement.", acceptedAnswers: ["plaques", "plaques tectoniques"] },
        { id: "svt-ag-q05", type: "true-false", prompt: "Un volcan se forme lorsque du magma remonte à la surface de la Terre.", correct: true },
        { id: "svt-ag-q06", type: "qcm", prompt: "Quelle échelle mesure la magnitude d'un séisme ?", options: ["L'échelle de Richter", "L'échelle de Celsius", "L'échelle de Beaufort", "L'échelle de pH"], correctIndex: 0 },
        { id: "svt-ag-q07", type: "qcm", prompt: "Que désigne le terme « magma » ?", options: ["De la roche en fusion sous la surface terrestre", "De l'eau souterraine", "Du sable volcanique", "De la lave refroidie"], correctIndex: 0 },
        { id: "svt-ag-q08", type: "true-false", prompt: "La lave est le magma qui a atteint la surface terrestre.", correct: true },
        { id: "svt-ag-q09", type: "fill-blank", prompt: "Les zones où se concentrent la plupart des séismes et volcans sont situées aux ___ des plaques tectoniques.", acceptedAnswers: ["limites", "frontières"] },
        { id: "svt-ag-q10", type: "qcm", prompt: "Quel phénomène peut être provoqué par un séisme sous-marin ?", options: ["Un tsunami", "Une sécheresse", "Une éclipse", "Une canicule"], correctIndex: 0 },
      ],
    },
  ],
};
