import type { Subject } from "../types";

export const svt: Subject = {
  id: "svt",
  name: "SVT",
  icon: "🧬",
  colorFrom: "from-lime-500",
  colorTo: "to-green-600",
  chapters: [
    {
      id: "revision-5eme-respiration",
      title: "Révision 5ème : respiration et milieux",
      description: "Échanges gazeux et peuplement des milieux de vie",
      icon: "🌿",
      exercises: [
        {
          id: "svt-r5-q01",
          type: "qcm",
          prompt: "Où les poissons trouvent-ils le dioxygène nécessaire à leur respiration ?",
          options: ["Dans l'eau", "Dans l'air uniquement", "Dans la terre", "Ils n'en ont pas besoin"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q02",
          type: "true-false",
          prompt: "Les organes respiratoires permettent les échanges gazeux entre l'organisme et son milieu.",
          correct: true,
        },
        {
          id: "svt-r5-q03",
          type: "qcm",
          prompt: "Quel organe respiratoire utilisent les poissons ?",
          options: ["Les branchies", "Les poumons", "La trachée", "La peau uniquement"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q04",
          type: "qcm",
          prompt: "Quel organe respiratoire utilisent les mammifères ?",
          options: ["Les poumons", "Les branchies", "Les trachées", "Les stomates"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q05",
          type: "fill-blank",
          prompt: "Le ___ est le gaz indispensable à la respiration, prélevé dans le milieu de vie.",
          acceptedAnswers: ["dioxygène", "oxygène"],
        },
        {
          id: "svt-r5-q06",
          type: "true-false",
          prompt: "La répartition des êtres vivants dans un milieu dépend des conditions de vie (température, eau, lumière...).",
          correct: true,
        },
        {
          id: "svt-r5-q07",
          type: "qcm",
          prompt: "Quel facteur peut limiter la présence d'un être vivant dans un milieu ?",
          options: [
            "Le manque de nourriture ou d'eau",
            "La couleur du ciel",
            "Le bruit uniquement",
            "Aucun facteur ne limite la présence",
          ],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q08",
          type: "fill-blank",
          prompt: "Un ensemble d'êtres vivants et de leur milieu de vie qui interagissent forme un ___.",
          acceptedAnswers: ["écosystème"],
        },
        {
          id: "svt-r5-q09",
          type: "qcm",
          prompt: "Comment les insectes respirent-ils généralement ?",
          options: ["Par des trachées", "Par des branchies", "Par des poumons", "Par la peau uniquement"],
          correctIndex: 0,
        },
        {
          id: "svt-r5-q10",
          type: "true-false",
          prompt: "Le peuplement d'un milieu peut changer au cours des saisons.",
          correct: true,
        },
      ],
    },
    {
      id: "reproduction-heredite",
      title: "Reproduction et hérédité",
      description: "Fécondation, chromosomes et caractères héréditaires (4ème)",
      icon: "🧬",
      exercises: [
        {
          id: "svt-rh-q01",
          type: "qcm",
          prompt: "Quel est le rôle des spermatozoïdes ?",
          options: ["Féconder l'ovule", "Produire du lait", "Digérer les aliments", "Filtrer le sang"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q02",
          type: "true-false",
          prompt: "La fécondation a lieu dans l'utérus.",
          correct: false,
          explanation: "La fécondation a lieu dans les trompes (oviductes) ; l'embryon se développe ensuite dans l'utérus.",
        },
        {
          id: "svt-rh-q03",
          type: "qcm",
          prompt: "Combien de chromosomes possède une cellule humaine normale ?",
          options: ["23", "46", "92", "12"],
          correctIndex: 1,
        },
        {
          id: "svt-rh-q04",
          type: "fill-blank",
          prompt: "Le brassage des chromosomes lors de la formation des cellules reproductrices est appelé la ___.",
          acceptedAnswers: ["meiose", "méiose"],
        },
        {
          id: "svt-rh-q05",
          type: "qcm",
          prompt: "Qu'est-ce qu'un caractère héréditaire ?",
          options: [
            "Un trait transmis des parents aux enfants",
            "Une maladie contagieuse",
            "Un comportement appris",
            "Un trait acquis pendant la vie",
          ],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q06",
          type: "true-false",
          prompt: "Les jumeaux identiques (vrais jumeaux) ont exactement le même ADN.",
          correct: true,
        },
        {
          id: "svt-rh-q07",
          type: "qcm",
          prompt: "Où se déroule la fécondation chez les mammifères ?",
          options: ["Dans les trompes (oviductes)", "Dans l'utérus", "Dans les ovaires", "Dans le vagin"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q08",
          type: "fill-blank",
          prompt: "Les chromosomes sont situés dans le ___ de la cellule.",
          acceptedAnswers: ["noyau"],
        },
        {
          id: "svt-rh-q09",
          type: "qcm",
          prompt: "Qu'apporte le spermatozoïde lors de la fécondation ?",
          options: ["23 chromosomes", "46 chromosomes", "De la nourriture", "Rien"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q10",
          type: "true-false",
          prompt: "Un gène peut exister sous plusieurs versions appelées allèles.",
          correct: true,
        },
        {
          id: "svt-rh-q11",
          type: "qcm",
          prompt: "Quel organe produit les spermatozoïdes ?",
          options: ["Les testicules", "Les ovaires", "Le pancréas", "Le foie"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q12",
          type: "qcm",
          prompt: "Quel organe produit les ovules ?",
          options: ["Les ovaires", "Les testicules", "L'utérus", "Le vagin"],
          correctIndex: 0,
        },
        {
          id: "svt-rh-q13",
          type: "fill-blank",
          prompt: "L'organe où se développe l'embryon puis le fœtus est l'___.",
          acceptedAnswers: ["utérus"],
        },
        {
          id: "svt-rh-q14",
          type: "true-false",
          prompt: "Le caryotype humain est composé de 23 paires de chromosomes.",
          correct: true,
        },
        {
          id: "svt-rh-q15",
          type: "qcm",
          prompt: "Quelle structure relie le fœtus au placenta ?",
          options: ["Le cordon ombilical", "La trompe", "L'oviducte", "L'urètre"],
          correctIndex: 0,
        },
      ],
    },
  ],
};
