import type { Subject } from "../types";

export const techno: Subject = {
  id: "techno",
  name: "Techno",
  icon: "🔧",
  colorFrom: "from-orange-500",
  colorTo: "to-red-600",
  chapters: [
    {
      id: "revision-5eme-objets",
      title: "Révision 5ème : objets et matériaux",
      description: "Fonctions d'un objet, familles de matériaux, énergie",
      icon: "🛠️",
      exercises: [
        {
          id: "techno-r5-q01",
          type: "qcm",
          prompt: "Qu'est-ce que la « fonction d'usage » d'un objet ?",
          options: ["Ce à quoi il sert", "Son prix", "Sa couleur", "Sa marque"],
          correctIndex: 0,
        },
        {
          id: "techno-r5-q02",
          type: "true-false",
          prompt: "La fonction d'estime correspond à l'aspect esthétique d'un objet (forme, couleur, style).",
          correct: true,
        },
        {
          id: "techno-r5-q03",
          type: "qcm",
          prompt: "Lequel de ces matériaux est un métal ?",
          options: ["Acier", "Bois", "Plastique", "Verre"],
          correctIndex: 0,
        },
        {
          id: "techno-r5-q04",
          type: "qcm",
          prompt: "Quelle énergie utilise une éolienne ?",
          options: ["L'énergie du vent", "L'énergie solaire", "L'énergie thermique", "L'énergie chimique"],
          correctIndex: 0,
        },
        {
          id: "techno-r5-q05",
          type: "fill-blank",
          prompt: "Le schéma qui représente le fonctionnement d'un objet avec ses entrées et sorties d'énergie s'appelle une chaîne d'___.",
          acceptedAnswers: ["énergie"],
        },
        {
          id: "techno-r5-q06",
          type: "true-false",
          prompt: "Le plastique est un matériau généralement d'origine pétrolière.",
          correct: true,
        },
        {
          id: "techno-r5-q07",
          type: "qcm",
          prompt: "Quel outil sert à mesurer une longueur ?",
          options: ["Une règle graduée", "Un thermomètre", "Une balance", "Un chronomètre"],
          correctIndex: 0,
        },
        {
          id: "techno-r5-q08",
          type: "qcm",
          prompt: "Qu'est-ce qu'un croquis technique ?",
          options: [
            "Un dessin rapide à main levée représentant un objet",
            "Une photo professionnelle",
            "Une recette de fabrication",
            "Un calcul de prix",
          ],
          correctIndex: 0,
        },
        {
          id: "techno-r5-q09",
          type: "fill-blank",
          prompt: "Une source d'énergie qui ne s'épuise pas, comme le soleil ou le vent, est dite ___.",
          acceptedAnswers: ["renouvelable"],
        },
        {
          id: "techno-r5-q10",
          type: "true-false",
          prompt: "Le recyclage permet de réutiliser des matériaux pour fabriquer de nouveaux objets.",
          correct: true,
        },
      ],
    },
    {
      id: "objets-programmables",
      title: "Objets techniques programmables",
      description: "Capteurs, microcontrôleurs et automatisation (4ème)",
      icon: "🤖",
      exercises: [
        {
          id: "techno-op-q01",
          type: "qcm",
          prompt: "Qu'est-ce qu'un algorithme ?",
          options: [
            "Une suite d'instructions pour résoudre un problème",
            "Un type de matériau",
            "Un capteur électronique",
            "Une unité de mesure",
          ],
          correctIndex: 0,
        },
        {
          id: "techno-op-q02",
          type: "true-false",
          prompt: "Un capteur permet de mesurer une grandeur physique (température, lumière...).",
          correct: true,
        },
        {
          id: "techno-op-q03",
          type: "qcm",
          prompt: "Quel composant agit comme le « cerveau » d'un objet programmable (ex. carte Arduino) ?",
          options: ["Le microcontrôleur", "La résistance", "Le condensateur", "Le capteur"],
          correctIndex: 0,
        },
        {
          id: "techno-op-q04",
          type: "fill-blank",
          prompt: "Un objet qui réagit automatiquement à son environnement grâce à des capteurs est dit ___.",
          acceptedAnswers: ["automatisé", "autonome"],
        },
        {
          id: "techno-op-q05",
          type: "qcm",
          prompt: "Lequel de ces matériaux est un métal ?",
          options: ["Aluminium", "Bois", "Plastique", "Verre"],
          correctIndex: 0,
        },
        {
          id: "techno-op-q06",
          type: "true-false",
          prompt: "Un actionneur transforme une énergie en mouvement ou en action (ex. un moteur).",
          correct: true,
        },
        {
          id: "techno-op-q07",
          type: "qcm",
          prompt: "Que signifie CAO ?",
          options: [
            "Conception Assistée par Ordinateur",
            "Création Automatique d'Objets",
            "Calcul Automatisé d'Opérations",
            "Construction Assistée par Ordinateur",
          ],
          correctIndex: 0,
        },
        {
          id: "techno-op-q08",
          type: "fill-blank",
          prompt: "Le ___ d'un objet technique décrit les fonctions qu'il doit remplir avant sa conception.",
          acceptedAnswers: ["cahier des charges"],
        },
        {
          id: "techno-op-q09",
          type: "qcm",
          prompt: "Quelle énergie utilise un panneau solaire ?",
          options: ["L'énergie solaire", "L'énergie éolienne", "L'énergie thermique", "L'énergie hydraulique"],
          correctIndex: 0,
        },
        {
          id: "techno-op-q10",
          type: "true-false",
          prompt: "Une chaîne d'énergie décrit comment l'énergie est transformée et transmise dans un objet technique.",
          correct: true,
        },
        {
          id: "techno-op-q11",
          type: "qcm",
          prompt: "Quel est le rôle d'un engrenage ?",
          options: [
            "Transmettre et transformer un mouvement",
            "Stocker de l'énergie",
            "Mesurer une distance",
            "Produire de la lumière",
          ],
          correctIndex: 0,
        },
        {
          id: "techno-op-q12",
          type: "qcm",
          prompt: "Lequel de ces éléments est un matériau composite ?",
          options: ["La fibre de carbone", "Le fer", "L'or", "L'eau"],
          correctIndex: 0,
        },
        {
          id: "techno-op-q13",
          type: "true-false",
          prompt: "Le bois est un matériau renouvelable.",
          correct: true,
        },
        {
          id: "techno-op-q14",
          type: "qcm",
          prompt: "Quel test permet de vérifier la solidité d'une structure ?",
          options: [
            "Un test de résistance / charge",
            "Un test de couleur",
            "Un test de goût",
            "Un test de température uniquement",
          ],
          correctIndex: 0,
        },
        {
          id: "techno-op-q15",
          type: "fill-blank",
          prompt: "Une vis et un boulon sont des éléments d'___ qui permettent de relier deux pièces.",
          acceptedAnswers: ["assemblage", "fixation"],
        },
      ],
    },
    {
      id: "conception-realisation",
      title: "Conception et réalisation d'objets",
      description: "CAO, prototypage, impression 3D et écoconception",
      icon: "🖨️",
      exercises: [
        { id: "techno-cr-q01", type: "qcm", prompt: "Que signifie l'impression 3D ?", options: ["Fabriquer un objet en ajoutant de la matière couche par couche", "Découper une pièce dans un bloc", "Peindre un objet", "Assembler des pièces existantes"], correctIndex: 0 },
        { id: "techno-cr-q02", type: "true-false", prompt: "La CAO (Conception Assistée par Ordinateur) permet de modéliser un objet en 3D avant sa fabrication.", correct: true },
        { id: "techno-cr-q03", type: "qcm", prompt: "Qu'est-ce qu'une contrainte de conception ?", options: ["Une limite à respecter (coût, taille, matériau...)", "Une décoration", "Un bonus", "Une option facultative"], correctIndex: 0 },
        { id: "techno-cr-q04", type: "fill-blank", prompt: "Un objet conçu pour durer et limiter son impact sur l'environnement est dit ___.", acceptedAnswers: ["écoconçu", "durable"] },
        { id: "techno-cr-q05", type: "true-false", prompt: "Un prototype est une première version d'un objet permettant de le tester avant la production finale.", correct: true },
        { id: "techno-cr-q06", type: "qcm", prompt: "Quel type de logiciel utilise-t-on pour la CAO ?", options: ["Un logiciel de modélisation 3D", "Un tableur", "Un traitement de texte", "Un lecteur vidéo"], correctIndex: 0 },
        { id: "techno-cr-q07", type: "qcm", prompt: "Quelle est une contrainte économique dans la conception d'un objet ?", options: ["Le coût de fabrication", "La couleur préférée", "Le nombre d'utilisateurs", "La météo"], correctIndex: 0 },
        { id: "techno-cr-q08", type: "true-false", prompt: "Le recyclage des matériaux fait partie de l'écoconception.", correct: true },
        { id: "techno-cr-q09", type: "fill-blank", prompt: "Avant de fabriquer un objet, on réalise souvent un ___ pour le tester.", acceptedAnswers: ["prototype"] },
        { id: "techno-cr-q10", type: "qcm", prompt: "Quel est l'avantage principal de l'impression 3D ?", options: ["Fabriquer des formes complexes rapidement", "Ne jamais utiliser de matière", "Être gratuite", "Ne nécessiter aucun logiciel"], correctIndex: 0 },
      ],
    },
    {
      id: "reseaux-communication",
      title: "Réseaux et communication numérique",
      description: "Internet, sécurité informatique et protocoles de base",
      icon: "🌐",
      exercises: [
        { id: "techno-rc-q01", type: "qcm", prompt: "Qu'est-ce qu'internet ?", options: ["Un réseau mondial d'ordinateurs interconnectés", "Un seul ordinateur très puissant", "Un logiciel de messagerie", "Un type de câble"], correctIndex: 0 },
        { id: "techno-rc-q02", type: "true-false", prompt: "Un mot de passe sécurisé doit être long et contenir des caractères variés.", correct: true },
        { id: "techno-rc-q03", type: "qcm", prompt: "Que désigne le « Wi-Fi » ?", options: ["Une technologie de connexion sans fil", "Un type de câble réseau", "Un logiciel antivirus", "Un moteur de recherche"], correctIndex: 0 },
        { id: "techno-rc-q04", type: "fill-blank", prompt: "L'adresse qui identifie un site web s'appelle une ___.", acceptedAnswers: ["url", "URL"] },
        { id: "techno-rc-q05", type: "true-false", prompt: "Il faut être prudent avant de partager des informations personnelles en ligne.", correct: true },
        { id: "techno-rc-q06", type: "qcm", prompt: "Qu'est-ce qu'un réseau local (LAN) ?", options: ["Un réseau limité à un espace restreint (maison, école...)", "Un réseau mondial", "Un type de virus", "Un moteur de recherche"], correctIndex: 0 },
        { id: "techno-rc-q07", type: "qcm", prompt: "Que faut-il faire si on reçoit un message suspect demandant des informations personnelles ?", options: ["Ne pas répondre et le signaler", "Répondre avec ses informations", "Transférer à tous ses amis", "Cliquer sur tous les liens"], correctIndex: 0 },
        { id: "techno-rc-q08", type: "true-false", prompt: "Un antivirus protège un ordinateur contre certains logiciels malveillants.", correct: true },
        { id: "techno-rc-q09", type: "fill-blank", prompt: "Le sigle HTTP désigne un ___ utilisé pour transférer des pages web.", acceptedAnswers: ["protocole"] },
        { id: "techno-rc-q10", type: "qcm", prompt: "Que signifie le cadenas affiché dans la barre d'adresse d'un navigateur ?", options: ["La connexion au site est sécurisée (HTTPS)", "Le site est gratuit", "Le site est bloqué", "Le site est lent"], correctIndex: 0 },
      ],
    },
  ],
};
